// Item sprites: food and farm items (crops, seeds). Fixed colours, modelled on the vanilla
// 16×16 item textures. See draw.js for the format.

const s = (pal, rows) => ({ pal, rows });

// --- fruit ------------------------------------------------------------------
const APPLE = [
  '................',
  '........tggg....',
  '........tGg.....',
  '...ooo.ot.ooo...',
  '..ohhRRoRRRRRo..',
  '.ohHhRRRRRRRRRo.',
  '.ohHRRRRRRRRRRo.',
  '.ohRRRRRRRRRRDo.',
  '.oRRRRRRRRRRRDo.',
  '.oRRRRRRRRRRDDo.',
  '.oRRRRRRRRRRDDo.',
  '..oRRRRRRRRDDo..',
  '..oDRRRRRRDDDo..',
  '...oDDDooDDDo...',
  '....ooo..ooo....',
  '................',
];
const STEM = { t: '#5a3a14', g: '#3e8a1d', G: '#6cc236' };

// --- bowls ------------------------------------------------------------------
const BOWL = { R: '#9a6a34', B: '#74502a', b: '#54391a', o: '#2a1a0a' };
const SOUP = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '....oooooooo....',
  '..ooSSSSSSSSoo..',
  '.oSSSsSSSSSSSSo.',
  'oRSSSSSSsSSSSSRo',
  'oRRSSSSSSSSSSRRo',
  'oBRRRRRRRRRRRRBo',
  '.oBBBBBBBBBBBBo.',
  '..obBBBBBBBBbo..',
  '...oobbbbbboo...',
  '.....oooooo.....',
  '................',
];
const STEW = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '....oooooooo....',
  '..ooSScSSpSSoo..',
  '.oSpSSSScSSSSSo.',
  'oRSSScSSSSpSSSRo',
  'oRRSSSSpSScSSRRo',
  'oBRRRRRRRRRRRRBo',
  '.oBBBBBBBBBBBBo.',
  '..obBBBBBBBBbo..',
  '...oobbbbbboo...',
  '.....oooooo.....',
  '................',
];

// --- meat -------------------------------------------------------------------
const BEEF = [
  '................',
  '................',
  '................',
  '......oooooo....',
  '....oohRRRRRoo..',
  '...ohhWRRRRRRo..',
  '..ohRWRRRRWRRRo.',
  '.ohRWRRRRWRRRRo.',
  '.oRWRRRRWRRRRDo.',
  '.oRRRRRWRRRRDDo.',
  '.oRRRRWRRRRDDo..',
  '..oRRWRRRDDDo...',
  '...ooRRDDDoo....',
  '.....ooooo......',
  '................',
  '................',
];
const PORKCHOP = [
  '................',
  '................',
  '................',
  '.....oooooo.....',
  '...ooFFFFFFoo...',
  '..oFFPPPPPPFFo..',
  '.oFPPhhPPPPPPFo.',
  '.oFPhPPPPPPPPFo.',
  '.oFPPPPPPPPPDFo.',
  '.oFPPPPPPPPDDFo.',
  '..oFPPPPPPDDFo..',
  '...oFFPPPDDFo...',
  '....ooFFFFoo....',
  '......oooo......',
  '................',
  '................',
];
const CHICKEN = [
  '................',
  '.............oo.',
  '............owwo',
  '...........oBwwo',
  '..........oBBBo.',
  '...oooooooBBBo..',
  '..oChhCCCoBBo...',
  '.oChCCCCCCoBo.oo',
  '.oCCCCCCCCCoBBwo',
  '.oCCCCCCCCDoBBo.',
  '.oCCCCCCCDDDoo..',
  '.oDCCCCCCDDDo...',
  '..oDDCCDDDDo....',
  '...oooooooo.....',
  '................',
  '................',
];
const MUTTON = [
  '................',
  '..oo............',
  '.owwo...........',
  '.owwwo..........',
  '..owwo..........',
  '...owwoooo......',
  '....owRRRRoo....',
  '....oRRWRRRRo...',
  '...oRRRRWRRRRo..',
  '...oRWRRRRRRRo..',
  '...oRRRRWRRRDo..',
  '...oRRRRRRRDDo..',
  '....oRRRRRDDo...',
  '.....ooDDDDo....',
  '.......oooo.....',
  '................',
];
const RABBIT = [
  '................',
  '................',
  '................',
  '..oo............',
  '.ohRo...........',
  '.oRRRoooooooo...',
  '.oRRRhhRRRRRRoo.',
  '..oRRRRRRRRRRRRo',
  '...oRRRRRRRRRRDo',
  '...oDRRRRRRRRDDo',
  '....oDoooooDDDo.',
  '....oRo....oDRo.',
  '...oRRo.....oRRo',
  '...ooo.......ooo',
  '................',
  '................',
];

// --- fish -------------------------------------------------------------------
const FISH = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '....oooooo....oo',
  '..ooGGGGGGoo.oTo',
  '.oeGGgGGGgGGooTo',
  'oGGGGGGGGGGGGTTo',
  'oBBGGGgGGGGGGTTo',
  '.oBBBBBBBBBBooTo',
  '..ooBBBBBBoo.oTo',
  '....oooooo....oo',
  '................',
  '................',
  '................',
];
const TROPICAL = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '....oooooo....oo',
  '..ooOOWOOWoo.oTo',
  '.oeOOOWOOOWOooTo',
  'oOOOOOWOOOWOOTTo',
  'oOOOOOWOOOWOOTTo',
  '.oOOOOWOOOWOooTo',
  '..ooOOWOOWoo.oTo',
  '....oooooo....oo',
  '................',
  '................',
  '................',
];

// --- crops and seeds --------------------------------------------------------
const CARROT = [
  '............g.g.',
  '..........g.gGg.',
  '...........gGGgg',
  '..........ogGGg.',
  '.........oYOkg..',
  '........oYOODo..',
  '.......oYOLDo...',
  '......oYOODo....',
  '.....oYOODo.....',
  '....oYLODo......',
  '...oYOODo.......',
  '...oOODo........',
  '..oOODo.........',
  '..oODo..........',
  '.oDo............',
  '.o..............',
];
const POTATO = [
  '................',
  '................',
  '................',
  '................',
  '......oooo......',
  '....ooPPPPoo....',
  '...oPpPPPPPPo...',
  '..oPpPPPsPPPPo..',
  '..oPPPPPPPPPdo..',
  '..oPPsPPPPPPdo..',
  '..oPPPPPPPPddo..',
  '...oPPPPsPddo...',
  '....oddPPddo....',
  '.....oooooo.....',
  '................',
  '................',
];
const BIG_SEEDS = [
  '................',
  '................',
  '................',
  '.....lA.........',
  '....AAd...lA....',
  '....dd...AAd....',
  '.........dd.....',
  '................',
  '................',
  '....lA..........',
  '...AAd....lA....',
  '...dd....AAd....',
  '.........dd.....',
  '................',
  '................',
  '................',
];
const BERRIES = [
  '......gGGg......',
  '.......gg.......',
  '......g..g......',
  '.....g....g.....',
  '....ooo..ooo....',
  '...ohRRoohRRo...',
  '...oRRRooRRRo...',
  '...oRRDooRRDo...',
  '....oooooooo....',
  '......ohRRo.....',
  '......oRRRo.....',
  '......oRRDo.....',
  '.......ooo......',
  '................',
  '................',
  '................',
];
const CHORUS = [
  '................',
  '................',
  '......oooo......',
  '....ooPpPPoo....',
  '...oPpLPPPdPo...',
  '..oPLPPdPPPPPo..',
  '..oPPPPPPpPdPo..',
  '.oPPdPPPPPPPPdo.',
  '.oPpPPPdPPPPPdo.',
  '.oPPPPPPPPdPDDo.',
  '..oPPdPPPPPPDo..',
  '..oPPPPPdPDDDo..',
  '...oDPPPPDDDo...',
  '....ooDDDDoo....',
  '......oooo......',
  '................',
];
const MELON = [
  '................',
  '................',
  '................',
  '................',
  '.oooooooooooooo.',
  '.ogFFFFFFFFFFgo.',
  '.ogRRkRRRRkRRgo.',
  '..ogRRRRkRRRgo..',
  '...ogRRkRRRgo...',
  '...oGgRRRRgGo...',
  '....oGggggGo....',
  '.....oGGGGo.....',
  '......oooo......',
  '................',
  '................',
  '................',
];

export const sprites = {
  apple: s({ ...STEM, o: '#4a0d0d', D: '#9e1414', R: '#d0251f', h: '#ee5b4f', H: '#ffd1cc' }, APPLE),
  golden_apple: s({ ...STEM, o: '#5a3a00', D: '#c88a10', R: '#f2c230', h: '#fde56a', H: '#ffffff' }, APPLE),
  bread: s({ o: '#4a2a0a', L: '#c8913a', l: '#e3b55e', B: '#9a6420', d: '#8a5418' }, [
    '................',
    '..........oooo..',
    '.........ollLLo.',
    '.......oolBLLLo.',
    '......ollLLBLLdo',
    '.....ollLLLLLdo.',
    '....ollBLLLLddo.',
    '...ollLLBLLddo..',
    '..ollLLLLLddo...',
    '.ollBLLLLddo....',
    'ollLLBLddoo.....',
    'olLLLLddo.......',
    '.oLLLddo........',
    '..oLddo.........',
    '...ooo..........',
    '................',
  ]),
  cookie: s({ o: '#4f2a0e', C: '#c9853f', l: '#dea05a', k: '#4a2410', d: '#9a5e28' }, [
    '................',
    '................',
    '.....oooooo.....',
    '...oollCCCCoo...',
    '..olCkCCCCCCCo..',
    '..olCCCCCCkCCo..',
    '.olCCCCCCCCCCdo.',
    '.oCkCCCkCCCCCdo.',
    '.oCCCCCCCCCkCdo.',
    '.oCCCCCCCCCCddo.',
    '.oCCkCCCCkCCddo.',
    '..oCCCCCCCCddo..',
    '..odCCCkCCdddo..',
    '...ooddddddoo...',
    '.....oooooo.....',
    '................',
  ]),
  cake: s({ o: '#3a2010', W: '#f4f4f0', G: '#c8c8c0', r: '#d8262a', S: '#b4683a', s: '#7e4420', C: '#f0e6d8' }, [
    '................',
    '................',
    '................',
    '................',
    '...oooooooooo...',
    '..oWWWWWWWWWWo..',
    '.oWWrWWWWWWrWWo.',
    '.oWWWWWrWWWWWWo.',
    '.oGWWrWWWWWWWGo.',
    '.oSWSGWSSWGSWSo.',
    '.oSSSSSSSSSSSso.',
    '.oCCCCCCCCCCCCo.',
    '.oSSSSSSSSSSsso.',
    '.osssssssssssso.',
    '..oooooooooooo..',
    '................',
  ]),
  pumpkin_pie: s({ o: '#4a2a0c', C: '#e3b06a', c: '#a8743a', P: '#e07a1c', p: '#f2a04a' }, [
    '................',
    '................',
    '................',
    '....oooooooo....',
    '..ooCCCCCCCCoo..',
    '.oCCPPPPPPPPCCo.',
    'oCPPPpPPPPPPpPCo',
    'oCPPPPPPPpPPPPCo',
    'oCPpPPPPPPPPPPCo',
    'oCCPPPPPpPPPPCCo',
    'ocCCPPPPPPPPCCco',
    'occCCCCCCCCCCcco',
    'occcccccccccccco',
    '.occcccccccccco.',
    '..oooooooooooo..',
    '................',
  ]),
  carrot: s({ o: '#6b2e05', O: '#f08a1c', Y: '#ffb34a', D: '#c4600c', L: '#b0500a', g: '#3f9a1c', G: '#6fcf3a', k: '#1f5a0a' }, CARROT),
  golden_carrot: s({ o: '#5a3a00', O: '#f2c230', Y: '#fff08a', D: '#c88a10', L: '#b07808', g: '#e0b020', G: '#fde56a', k: '#8a6000' }, CARROT),
  potato: s({ o: '#5a4012', P: '#d9b35a', p: '#ecd08a', s: '#9a7a35', d: '#b08a3a' }, POTATO),
  baked_potato: s({ o: '#4a2a0a', P: '#c98a3a', p: '#f6dd7a', s: '#7a4a18', d: '#9a6224' }, POTATO),
  poisonous_potato: s({ o: '#3a4010', P: '#c6c56a', p: '#e0de90', s: '#5f8a2a', d: '#8f9a40' }, POTATO),
  beetroot: s({ o: '#3a0a14', B: '#a3263a', b: '#d0485c', D: '#6a1426', g: '#3e8a1d', G: '#6cc236', r: '#a3263a' }, [
    '.......gg.......',
    '.....gGgrgG.....',
    '......gGrGg.....',
    '.......rrr......',
    '.....ooorooo....',
    '....obbBBBBBo...',
    '...obBBBBBBBBo..',
    '..obBBBBBBBBBDo.',
    '..obBBBBBBBBBDo.',
    '..oBBBBBBBBBDDo.',
    '...oBBBBBBBDDo..',
    '....oBBBBBDDo...',
    '.....ooBBDDo....',
    '.......oDDo.....',
    '........oDo.....',
    '.........o......',
  ]),
  bowl: s({ ...BOWL, S: '#3a2610', s: '#4a3216' }, SOUP),
  beetroot_soup: s({ ...BOWL, S: '#a8202e', s: '#d04050' }, SOUP),
  mushroom_stew: s({ ...BOWL, S: '#c8a274', s: '#e6c89c', c: '#f0e2c4', p: '#8a5a3a' }, STEW),
  rabbit_stew: s({ ...BOWL, S: '#8a5a2a', s: '#b07a40', c: '#e0882a', p: '#e0c070' }, STEW),
  melon_slice: s({ o: '#2a3a0a', g: '#7cbf3a', G: '#3f7a1a', F: '#ff8a7a', R: '#e2322a', k: '#2a1a0a' }, MELON),
  glistering_melon_slice: s({ o: '#5a3a00', g: '#fde56a', G: '#d8a020', F: '#ffd0a0', R: '#e2322a', k: '#fff6b0' }, MELON),
  sweet_berries: s({ o: '#2a0606', R: '#b8201e', h: '#ee6a5a', D: '#6a0a0a', g: '#3e7a1d', G: '#6cb236' }, BERRIES),
  glow_berries: s({ o: '#5a3008', R: '#f0a020', h: '#fff08a', D: '#c06010', g: '#3e7a1d', G: '#6cb236' }, BERRIES),
  chorus_fruit: s({ o: '#2a102a', P: '#9a6a9a', p: '#c8a0c8', L: '#e8d4e8', d: '#5a305a', D: '#6a3a6a' }, CHORUS),
  popped_chorus_fruit: s({ o: '#3a1a3a', P: '#c49ac4', p: '#e0c8e0', L: '#fff0ff', d: '#7a4a7a', D: '#9a6a9a' }, CHORUS),
  dried_kelp: s({ o: '#0f1508', K: '#3a4a20', k: '#5a6a30', D: '#202a10' }, [
    '................',
    '...........ooo..',
    '..........okkKo.',
    '.........okKKDo.',
    '........okKKDo..',
    '.......okKDDo...',
    '......okKKDo....',
    '.....okKKDo.....',
    '....okKDDo......',
    '...okKKDo.......',
    '..okKKDo........',
    '..okKDo.........',
    '..oKDo..........',
    '...oo...........',
    '................',
    '................',
  ]),
  beef: s({ o: '#4a0a08', R: '#c8302a', h: '#e85a50', W: '#f0a098', D: '#8a1a14' }, BEEF),
  cooked_beef: s({ o: '#2a160a', R: '#7a4a2a', h: '#a06a3a', W: '#4a2a12', D: '#4a2a12' }, BEEF),
  porkchop: s({ o: '#6a2a2a', P: '#f08a8a', h: '#ffb8b0', D: '#c05a5a', F: '#f8dcd0' }, PORKCHOP),
  cooked_porkchop: s({ o: '#4a2810', P: '#b87a4a', h: '#d8a06a', D: '#8a5028', F: '#e8c890' }, PORKCHOP),
  chicken: s({ o: '#7a4a3a', C: '#f0c4b0', h: '#fff0e8', D: '#c8907a', B: '#e0a890', w: '#ffffff' }, CHICKEN),
  cooked_chicken: s({ o: '#4a2a10', C: '#d0904a', h: '#f0c080', D: '#9a5a24', B: '#b8763a', w: '#f0e0c0' }, CHICKEN),
  mutton: s({ o: '#4a0a08', R: '#c43a32', W: '#f0c0b8', D: '#8a1a14', w: '#f0eedc' }, MUTTON),
  cooked_mutton: s({ o: '#2a1408', R: '#8a5030', W: '#b07a50', D: '#5a3018', w: '#f0e6c8' }, MUTTON),
  rabbit: s({ o: '#7a3a34', R: '#eaa8a0', h: '#fff0ec', D: '#c07a72' }, RABBIT),
  cooked_rabbit: s({ o: '#4a2a10', R: '#c8884a', h: '#f0c080', D: '#8a5424' }, RABBIT),
  cod: s({ o: '#3a3020', e: '#101010', G: '#b0a080', g: '#8a7a5a', B: '#e0d8c0', T: '#8a7a5a' }, FISH),
  cooked_cod: s({ o: '#4a3418', e: '#2a1a0a', G: '#d8b88a', g: '#a8885a', B: '#f4e6c8', T: '#b8946a' }, FISH),
  salmon: s({ o: '#3a1410', e: '#101010', G: '#c85a40', g: '#8a3a2a', B: '#ec9a84', T: '#5a6a5a' }, FISH),
  cooked_salmon: s({ o: '#4a2410', e: '#2a1a0a', G: '#c87a4a', g: '#9a5a30', B: '#ecb888', T: '#8a5a3a' }, FISH),
  tropical_fish: s({ o: '#4a2008', e: '#101010', O: '#f08a1c', W: '#ffffff', T: '#f0b060' }, TROPICAL),
  pufferfish: s({ o: '#5a4010', Y: '#e8c040', g: '#8a7a30', L: '#f0e8b0', s: '#f0e8c0', e: '#101010', T: '#c8a030' }, [
    '................',
    '................',
    '....s.s..s......',
    '...ooooooooo....',
    '..oYYgYYYgYYo...',
    '.soYeYYYYYYYo.oo',
    '..oYYYYgYYYYYoTo',
    '.soYgYYYYYYYYTTo',
    '..oLLLLLLLLLLoTo',
    '.soLLLLLLLLLo.oo',
    '..oLLLLLLLLo....',
    '...oooooooo.....',
    '....s.s..s......',
    '................',
    '................',
    '................',
  ]),
  wheat: s({ o: '#7a5a10', W: '#dcb040', w: '#f0d878', S: '#b8902a', s: '#8a6a18' }, [
    '...........oo...',
    '.......oo.oWWo..',
    '......oWWooWwWo.',
    '.....oWwWWoWWWo.',
    '.....oWWwWWWwo..',
    '......oWWWwWWo..',
    '......SoWWWWo...',
    '.....SsSSs......',
    '....SsS.S.......',
    '...SsS.S........',
    '...sS.S.........',
    '..SsS...........',
    '..sS............',
    '.SS.............',
    '.S..............',
    '................',
  ]),
  wheat_seeds: s({ l: '#8ad04a', g: '#4a9a20', d: '#2a5a10' }, [
    '................',
    '................',
    '................',
    '......lg........',
    '......gd........',
    '..........lg....',
    '..........gd....',
    '...lg...........',
    '...gd...lg......',
    '........gd......',
    '............lg..',
    '.....lg.....gd..',
    '.....gd..lg.....',
    '.........gd.....',
    '................',
    '................',
  ]),
  pumpkin_seeds: s({ l: '#fbf5e0', A: '#e8d8a8', d: '#b8a070' }, BIG_SEEDS),
  melon_seeds: s({ l: '#6a5a4a', A: '#2a2018', d: '#100c08' }, BIG_SEEDS),
  beetroot_seeds: s({ l: '#e8d4b0', A: '#b89870', d: '#806040' }, BIG_SEEDS),
  torchflower_seeds: s({ l: '#a8c070', A: '#6a8a3a', d: '#3a5a20' }, BIG_SEEDS),
  pitcher_pod: s({ o: '#1a3a1a', T: '#6a9a5a', L: '#9ac88a', d: '#3a6a3a' }, [
    '................',
    '................',
    '................',
    '...........oo...',
    '..........oLTo..',
    '.........oLTTo..',
    '........oLTTdo..',
    '.......oLTTdo...',
    '......oLTTdo....',
    '.....oLTTdo.....',
    '....oTTTdo......',
    '....oTTdo.......',
    '....oddo........',
    '.....oo.........',
    '................',
    '................',
  ]),
  cocoa_beans: s({ o: '#24140a', B: '#7a4a22', L: '#a8743a', D: '#4a2a10' }, [
    '................',
    '................',
    '...oooo.........',
    '..oLBBBo........',
    '..oBBBDo........',
    '..oBBDDo.oooo...',
    '...oooo.oLBBBo..',
    '........oBBBDo..',
    '........oBBDDo..',
    '.....oooooooo...',
    '....oLBBBo......',
    '....oBBBDo......',
    '....oBBDDo......',
    '.....oooo.......',
    '................',
    '................',
  ]),
  nether_wart: s({ o: '#3a0505', R: '#a01a1a', h: '#d84040', D: '#6a0a0a', S: '#6a1a1a' }, [
    '................',
    '................',
    '.....oo.oo......',
    '....ohRohRo.....',
    '...oRRRRRRRoo...',
    '..ohRRDRRhRRRo..',
    '..oRRRRRRRRRDo..',
    '..oRDRRRRDRRDo..',
    '...oRRRRRRRDo...',
    '....ooRRRDoo....',
    '......oSSo......',
    '......oSSo......',
    '.......oo.......',
    '................',
    '................',
    '................',
  ]),
  sugar_cane: s({ G: '#8ad050', g: '#5a9a2a', k: '#bce68a', l: '#6ab83a' }, [
    '................',
    '.......Gg.......',
    '...Gg..Gg..Gg...',
    '...Gg..kk..Gg...',
    '...kk..Gg..Gg..l',
    '...Gg..Gg.lkk.l.',
    'l..Gg..Ggl.Gg.l.',
    '.l.Gg..kk..Gg...',
    '..lkk..Gg..Gg...',
    '...Gg..Gg..kk...',
    '...Gg..Gg..Gg...',
    '...Gg..kk..Gg...',
    '...kk..Gg..Gg...',
    '...Gg..Gg..kk...',
    '...Gg..Gg..Gg...',
    '................',
  ]),
  kelp: s({ o: '#1a3a0a', G: '#5a9a2a', g: '#3a7a1a' }, [
    '........o.......',
    '.......oGo......',
    '......oGgo......',
    '.....oGgo.oo....',
    '.....oGo.oGgo...',
    '......oGooGgo...',
    '.......oGGgo....',
    '.....oo.oGo.....',
    '....oGgooGo.....',
    '....oGgGGo......',
    '.....ooGo.......',
    '.......oGo......',
    '.......oGgo.....',
    '........oGo.....',
    '.........o......',
    '................',
  ]),
  bamboo: s({ o: '#2a4a0a', G: '#7ab83a', g: '#4a8a1a', K: '#a8d860', l: '#6ab030', L: '#3a7a1a' }, [
    '................',
    '............lL..',
    '..........oLLl..',
    '.........oGgo...',
    '........oGgo....',
    '.......oKKo.....',
    '......oGgo......',
    '.....oGgo.......',
    '....oGgo........',
    '...oKKo.........',
    '..oGgo..........',
    '.oGgo...........',
    '.ooo............',
    '................',
    '................',
    '................',
  ]),
};

export const rules = [
  [/^apple$/, 'apple'],
  [/^golden_apple$/, 'golden_apple'],
  [/^enchanted_golden_apple$/, 'golden_apple', { glint: true }],
  ...['bread', 'cookie', 'cake', 'pumpkin_pie', 'carrot', 'golden_carrot', 'potato', 'baked_potato', 'poisonous_potato', 'beetroot',
    'beetroot_soup', 'mushroom_stew', 'rabbit_stew', 'melon_slice', 'glistering_melon_slice', 'sweet_berries', 'glow_berries',
    'chorus_fruit', 'popped_chorus_fruit', 'dried_kelp', 'beef', 'cooked_beef', 'porkchop', 'cooked_porkchop', 'chicken',
    'cooked_chicken', 'mutton', 'cooked_mutton', 'rabbit', 'cooked_rabbit', 'cod', 'cooked_cod', 'salmon', 'cooked_salmon',
    'tropical_fish', 'pufferfish', 'wheat', 'wheat_seeds', 'pumpkin_seeds', 'melon_seeds', 'beetroot_seeds', 'torchflower_seeds',
    'pitcher_pod', 'cocoa_beans', 'nether_wart', 'sugar_cane', 'kelp', 'bamboo'].map(n => [new RegExp(`^${n}$`), n]),
  [/^suspicious_stew$/, 'mushroom_stew'],
  [/^bowl$/, 'bowl'],
  [/^seeds$/, 'wheat_seeds'],
];
