// Item sprites: materials, minerals, drops, dyes, books, bottles and discs. See draw.js for the
// format. Rows are written without trailing dots or blank bottom rows; `S` pads them to 16×16.
//
// Tinted templates use the material ramp: o outline · d dark · s shade · a base · l light · w glint.
import { DYES, dyeOf } from '../color.js';

const S = (pal, rows) => ({ pal, rows: [...rows, ...Array(Math.max(0, 16 - rows.length)).fill('')].map(r => r.padEnd(16, '.')) });
const TINT = { o: '@0', d: '@1', s: '@2', a: '@3', l: '@4', w: '@5' };
const TINT2 = { ...TINT, E: '%1', F: '%2', e: '%3', f: '%4', g: '%5' };

// glass bottles: g edge · G glass · h highlight · c/C cork; liquid uses the tint ramp
const GLASS = { g: '#4a5b63', G: '#9fc2cf', h: '#ffffff', i: '#ffffff40', c: '#b08a5c', C: '#6e5034' };
const BOTTLE_ROWS = [
  '',
  '',
  '......CccC',
  '......gCCg',
  '......gGhg',
  '......gh.g',
  '.....gh..ig',
  '....gh.....g',
  '...ghlaaaaasg',
  '...ghaaaaaasg',
  '...glaaaaaasg',
  '...gaaaaaassg',
  '...gaaaaassdg',
  '....gsssssdg',
  '.....gggggg',
];
const SPLASH_ROWS = [
  '',
  '',
  '.......CcC',
  '.......gCg',
  '.......ghg',
  '......gh.g',
  '.....gh...g',
  '....gh.....g',
  '...ghlaaaaasg',
  '..ghlaaaaaaasg',
  '..glaaaaaaaasg',
  '..gaaaaaaaassg',
  '..gaaaaaaassdg',
  '...gssssssddg',
  '....gggggggg',
];

// books: k outline · C cover · L cover light · D cover dark · p pages · P page shade · t trim
const BOOK_ROWS = [
  '',
  '',
  '....oooooooooo',
  '...oLLLLLLLLLCo',
  '..oLCCCCCCCCCDo',
  '..oLCCtCCCCCCDo',
  '..oLCCCCCCCCCDo',
  '..oLCCCCCCCCCDo',
  '..oLCCCCCCCCCDo',
  '..oLCCCCCCCCCDo',
  '..oLCCCCCCCCCDo',
  '..oLCCCCCCCCDDo',
  '..oLDDDDDDDDDpo',
  '..oopppppppppPo',
  '...oPPPPPPPPPo',
  '....ooooooooo',
];
const BOOK_PAL = { o: '#2a1508', C: '#7a3f1c', L: '#9c5a2c', D: '#5a2d12', p: '#f2ecd8', P: '#c9bfa5', t: '#7a3f1c' };

// Pottery sherd: a terracotta shard; each pattern is a 6×6 glyph pressed into it (E), with a
// lighter rim (l) below-right of every stroke.
const SHERD_ROWS = [
  '',
  '...oooo',
  '..owwlloo.ooo',
  '..owlaalloowlo',
  '..olaaaaallaaso',
  '..olaaaaaaaaaso',
  '.oolaaaaaaaaaaso',
  '.olaaaaaaaaaaaso',
  '.olaaaaaaaaaaaso',
  '.olaaaaaaaaaaaso',
  '.olaaaaaaaaaaaso',
  '.olaaaaaaaaaasso',
  '.oaaaaaaaaaassdo',
  '..ossssssssddo',
  '...oooooooooo',
];
const SHERD_GLYPHS = {
  angler: ['...#..', '...#..', '...#..', '#..#..', '#..#..', '.##...'],
  archer: ['...###', '....##', '...#.#', '..#...', '.#....', '#.....'],
  arms_up: ['#.##.#', '#.##.#', '.####.', '..##..', '.#..#.', '.#..#.'],
  blade: ['.....#', '....#.', '...#..', '#.#...', '.#....', '#.#...'],
  brewer: ['..##..', '..##..', '.#..#.', '#....#', '#.##.#', '.####.'],
  burn: ['..#...', '..##.#', '.#.##.', '#..#.#', '#....#', '.####.'],
  danger: ['##..##', '##..##', '..##..', '.####.', '.#..#.', '......'],
  explorer: ['######', '#..#.#', '#.#..#', '#...##', '##...#', '######'],
  flow: ['.####.', '#....#', '#.##.#', '#.#..#', '#..#..', '.##...'],
  friend: ['.#..#.', '######', '.#..#.', '.#..#.', '#.##.#', '......'],
  guster: ['.####.', '#....#', '#.##.#', '#.#..#', '#..##.', '.#....'],
  heart: ['.#..#.', '######', '######', '.####.', '..##..', '......'],
  heartbreak: ['.#..#.', '###.##', '##.###', '.#.##.', '..##..', '......'],
  howl: ['#....#', '##..##', '######', '#.##.#', '.####.', '..##..'],
  miner: ['.####.', '#.##.#', '..##..', '..##..', '..##..', '..##..'],
  mourner: ['..##..', '.####.', '#.##.#', '..##..', '.#..#.', '#....#'],
  plenty: ['######', '#.##.#', '######', '#....#', '#....#', '######'],
  prize: ['..##..', '.#..#.', '#....#', '.#..#.', '..##..', '......'],
  scrape: ['.###..', '####..', '.###..', '..#...', '..#...', '..#...'],
  sheaf: ['#.#.#.', '.###..', '..#...', '..#...', '.###..', '#.#.#.'],
  shelter: ['..##..', '.####.', '######', '..##..', '..##..', '..##..'],
  skull: ['.####.', '#....#', '#.##.#', '#....#', '.#..#.', '.####.'],
  snort: ['......', '.####.', '##..##', '######', '.##.##', '#.#.#.'],
};
const sherd = glyph => SHERD_ROWS.map((r, y) => [...r.padEnd(16, '.')].map((ch, x) => {
  const at = (gx, gy) => glyph[gy - 6]?.[gx - 5] === '#';
  if (at(x, y)) return 'E';
  return at(x - 1, y - 1) && ch === 'a' ? 'l' : ch;
}).join(''));

export const sprites = {
  // ---- metals -------------------------------------------------------------
  ingot: S(TINT, [
    '',
    '',
    '',
    '',
    '........ooooooo',
    '......oowlllllao',
    '....oowllllllaso',
    '..oowlllllllasdo',
    '.owllllllllasddo',
    '.oaaaaaaaaasddo',
    '.oaaaaaaaaasdo',
    '.osssssssssdo',
    '..ooooooooooo',
  ]),
  nugget: S(TINT, [
    '',
    '',
    '',
    '',
    '......oooo',
    '.....owlaaoo',
    '...oowlaaasao',
    '..owlwlaasaaso',
    '..olaaaaaaasdo',
    '..oasaaasaasdo',
    '...osaaassddo',
    '....oossddoo',
    '......oooo',
  ]),
  raw: S(TINT, [
    '', '', '',
    '......oooo',
    '....oowllaoo',
    '...owllaaasao',
    '..owlaasaaaaso',
    '..olaaaaasaasdo',
    '.owlasaaaaaaado',
    '.olaaaaaasaasdo',
    '.oaaasaaaaaasdo',
    '.osaaaaasaassdo',
    '..osssaassssdo',
    '...oddsssdddo',
    '....ooooooooo',
  ]),
  netherite_scrap: S(TINT2, [
    '', '', '',
    '.......ooo',
    '.....oowlaoo',
    '....owlaeasao',
    '...owlaeEaaaso',
    '..owlaasaaeaso',
    '..olaaaaeEasdo',
    '..oaeaaaaaasdo',
    '..osEaasaaasdo',
    '...osaaaeassdo',
    '....osssssddo',
    '.....ooooooo',
  ]),

  // ---- gems and crystals --------------------------------------------------
  diamond: S(TINT, [
    '', '', '',
    '....oooooooo',
    '...owwllllaao',
    '..owwlllaaaaso',
    '.owlllllaaaasso',
    '.oaaaaaaaaassdo',
    '..oaaaaaaassdo',
    '...oaaaaassdo',
    '....oaaassdo',
    '.....oassdo',
    '......osdo',
    '.......oo',
  ]),
  emerald: S(TINT, [
    '', '',
    '......oooo',
    '.....owwlao',
    '....owwllaao',
    '...owwllaaaso',
    '...owllaaaaso',
    '...owlaaaaaso',
    '...olaaaaaaso',
    '...oaaaaassdo',
    '....oaaassdo',
    '.....oassdo',
    '......oddo',
    '.......oo',
  ]),
  lapis: S(TINT, [
    '', '', '',
    '.......ooo',
    '.....oowlao',
    '....owllaasoo',
    '...owlaawasso',
    '..owlaaaaaasdo',
    '..olawaasaaasdo',
    '.owlaaaasaawsdo',
    '.olaasaaaaassdo',
    '.oaaaaaawsassdo',
    '..osssassssddo',
    '...oddsdddoo',
    '....ooooooo',
  ]),
  quartz: S(TINT, [
    '',
    '',
    '......ooo',
    '.....owwlo',
    '....owwllaoo',
    '...owwllaaaso',
    '..owwlllaaasso',
    '..owllllaaassdo',
    '..olllaaaassddo',
    '..olaaaaassdddo',
    '...oaaaassddo',
    '....oasssddo',
    '.....oosddo',
    '.......ooo',
  ]),
  amethyst_shard: S(TINT, [
    '',
    '...........oo',
    '..........owlo',
    '......oo..owlso',
    '.....owlo.olaso',
    '.....olaoowlaso',
    '....owlasolasso',
    '...owlasoolaso',
    '..owlasoolasso',
    '..olaasolassso',
    '.owlasoolasso',
    '.olaasolassdo',
    '.oaassasssdo',
    '.osssssddoo',
    '..ooooooo',
  ]),
  echo_shard: S({ o: '#03191c', d: '#0a2d33', s: '#0f4a52', a: '#136670', l: '#29dfeb', w: '#c3fbff' }, [
    '', '',
    '...........oo',
    '.........ooaso',
    '.......ooaalso',
    '......osaaaldo',
    '.....osaslasdo',
    '....osaslassdo',
    '...osaslassdo',
    '..osaalassddo',
    '..osalaassdo',
    '.osalwsssddo',
    '.oslwssdddo',
    '.oswsddooo',
    '..oooo',
  ]),
  prismarine_shard: S({ o: '#1c3c3a', d: '#2f6460', s: '#4c8d86', a: '#6cb0a6', l: '#95d3c7', w: '#d1f2ea' }, [
    '', '',
    '.........oo',
    '........owlo',
    '.......owlaso',
    '......owlaasdo',
    '.....owlaaasdo',
    '....owlwaasdo',
    '...owlaaasddo',
    '..owlaaasddo',
    '..olaaassdo',
    '.owlaassdo',
    '.olassddo',
    '.osdddoo',
    '..ooo',
  ]),
  prismarine_crystals: S({ o: '#3e6b62', s: '#8fc9b5', a: '#c3e8d6', l: '#e8fbf1', w: '#ffffff' }, [
    '', '',
    '........ooo',
    '.......olwlo',
    '...ooo.oawao',
    '..olwlo.olao.ooo',
    '..oawao..o..olwlo',
    '...olao.....oawao',
    '....o..ooo...olao',
    '......olwlo...o',
    '...ooooawao',
    '..olwlo.olao',
    '..oawao..o..ooo',
    '...olao....olwlo',
    '....o......oawao',
    '............olao',
  ].map(r => r.slice(0, 16))),
  nether_star: S({ o: '#6a6a4a', s: '#c8c89a', a: '#e6e6c0', l: '#f6f6e0', w: '#ffffff', y: '#f3f08a' }, [
    '',
    '.......oo',
    '......owlo',
    '......olao',
    '..oo..olao..oo',
    '..owoooaaoooso',
    '...olwwlaaaso',
    '....olwyyaso',
    '....oaayyaso',
    '...olaaaaasso',
    '..olaasoosaaso',
    '..oaso....osso',
    '.olso......osso',
    '.ooo........ooo',
  ]),

  flint: S(TINT, [
    '', '',
    '.........oo',
    '........owlo',
    '.......owllao',
    '......owlaaso',
    '.....owlaasdo',
    '....owlaasado',
    '...owlasaasdo',
    '...olaaasasdo',
    '..owlaasassdo',
    '..olaasassdo',
    '..oasassddo',
    '..ossddoo',
    '...ooo',
  ]),

  // ---- lumps and balls ----------------------------------------------------
  lump: S(TINT, [
    '', '', '',
    '......oooo',
    '....oolwlsoo',
    '...olwlassaso',
    '..olwlaasasaso',
    '..owlasaaassao',
    '.olaasaasasasdo',
    '.olasaaasaasdso',
    '.osaasasassasdo',
    '.oassasassdsddo',
    '..osdsassdsddo',
    '...oddsdddddo',
    '....oooooooo',
  ]),
  ball: S(TINT, [
    '', '', '', '',
    '......oooo',
    '....oowllaoo',
    '...owwlaaaaso',
    '..owwlaaaaaaso',
    '..owlaaaaaaaso',
    '..olaaaaaaaaso',
    '..oaaaaaaaasso',
    '..osaaaaaassdo',
    '...osssssdddo',
    '....ooddddoo',
    '......oooo',
  ]),
  slime_ball: S({ o: '#2f6b23', d: '#3f8a31', s: '#5aa847', a: '#7cc964', l: '#a4e08c', w: '#d7f7c9', k: '#3f8a31' }, [
    '', '', '', '',
    '......oooo',
    '....oowllaoo',
    '...owwlaaaaso',
    '..owwlaaaaaaso',
    '..owlaakkaaaso',
    '..olaakkkkaaso',
    '..oaaakkkkasso',
    '..osaaakkassdo',
    '...osssssdddo',
    '....ooddddoo',
    '......oooo',
  ]),
  magma_cream: S({ o: '#4a1a05', d: '#8a3a0a', s: '#c4610d', a: '#f08a1a', l: '#ffbd3b', w: '#fff08a', k: '#3a1a10' }, [
    '', '', '', '',
    '......oooo',
    '....oowllaoo',
    '...owwlakaaso',
    '..owwlaaaaaaso',
    '..owlkaaaakaso',
    '..olaaaawaaaso',
    '..oaakaaaaksso',
    '..osaaaakassdo',
    '...osskssdddo',
    '....ooddddoo',
    '......oooo',
  ]),
  ghast_tear: S({ o: '#5b7a85', d: '#8fb0bb', s: '#bcd8e0', a: '#ddeff4', l: '#f2fbfd', w: '#ffffff' }, [
    '',
    '',
    '',
    '.......oo',
    '......owlo',
    '......owlo',
    '.....owwlao',
    '.....owlaao',
    '....owwlaaso',
    '....owlaaaso',
    '....olaaaaso',
    '....osaaasdo',
    '.....ossddo',
    '......oooo',
  ]),
  heart_of_the_sea: S({ o: '#0e2a4a', d: '#14457a', s: '#1f6bb0', a: '#2f93d6', l: '#7fd0f0', w: '#e0fbff', k: '#0d3a63' }, [
    '', '',
    '......oooo',
    '....oowwlloo',
    '...owwlkkllao',
    '..owlkaaakkaso',
    '..olkallaaakso',
    '.owlkalwlaakaso',
    '.olaakalaaakaso',
    '.oaaaakkkkaasso',
    '.osaaaaaaaasssdo',
    '..osaaaaassddo',
    '..osssassddddo',
    '...oodddddoo',
    '.....oooooo',
  ].map(r => r.slice(0, 16))),
  heavy_core: S({ o: '#141416', d: '#2a2b30', s: '#3c3e45', a: '#50535c', l: '#6c707b', w: '#8c919c' }, [
    '', '', '',
    '....oooooooo',
    '...owwwllllao',
    '..owlllllllaao',
    '..olaaaaaaaaso',
    '..oladdddddaso',
    '..oladdaadaaso',
    '..oladdaadaaso',
    '..oladdddddaso',
    '..olaaaaaaaaso',
    '..oassssssssdo',
    '...oddddddddo',
    '....oooooooo',
  ]),

  // ---- dusts --------------------------------------------------------------
  dust: S(TINT, [
    '', '', '',
    '........w',
    '......l.lw',
    '.....wlalal',
    '....laalwaas',
    '...wlaasalasa',
    '..lalasaaasaas',
    '..alaasalaassd',
    '.wlasaaasaasdsd',
    '.aasasassasddsdo',
    '.osdsdsdsddddoo',
    '..oooooooooooo',
  ]),

  // ---- rods, bones, strings -----------------------------------------------
  stick: S({ l: '#896727', m: '#684e1e', d: '#493615', k: '#28190a' }, [
    '', '',
    '............dk',
    '...........lmd',
    '..........lmd',
    '.........lmd',
    '........lmd',
    '.......lmd',
    '......lmd',
    '.....lmd',
    '....lmd',
    '...lmd',
    '..lmd',
    '..dk',
  ]),
  rod: S(TINT, [
    '', '',
    '...........olo',
    '..........owlso',
    '..........olaso',
    '.........owlso',
    '........owlso',
    '.......owlso',
    '......owlso',
    '.....owlso',
    '....owlso',
    '...owlso',
    '..owlso',
    '..olaso',
    '..osso',
    '...oo',
  ]),
  breeze_rod: S({ o: '#2b3352', d: '#4a5788', s: '#6d7fbf', a: '#94a6e6', l: '#c0ccf7', w: '#eef2ff' }, [
    '', '',
    '...........oo',
    '..........owlo',
    '..........olso',
    '.........owdo',
    '........olaso',
    '.......owdlo',
    '......olaso',
    '.....owdlo',
    '....olaso',
    '...owdlo',
    '..olaso',
    '..osdo',
    '...oo',
  ]),
  bone: S({ o: '#6b6553', s: '#b5ae94', a: '#d8d2b8', l: '#ece8d6', w: '#ffffff' }, [
    '',
    '..........oo.oo',
    '.........owwowlo',
    '.........owllllo',
    '..........owlso',
    '.........owlso',
    '........owlso',
    '.......owlso',
    '......owlso',
    '.....owlso',
    '....owlso',
    '...owlso',
    '.owllaso',
    '.olasaaso',
    '.osoosso',
    '..o..oo',
  ]),
  string: S({ w: '#ffffff', l: '#dcdcdc', s: '#a8a8a8' }, [
    '', '',
    '...........wl',
    '..........w..s',
    '.........l...w',
    '.........w..l',
    '..........ls',
    '.........w',
    '........l',
    '.......w',
    '......l..wls',
    '.....w..s...w',
    '.....l..w..l',
    '......ws..l',
    '.........s',
  ]),
  feather: S({ o: '#6e6e6e', s: '#bdbdbd', l: '#e6e6e6', w: '#ffffff', q: '#8f8f8f' }, [
    '',
    '............oo',
    '...........owlo',
    '..........owlwo',
    '.........owlwso',
    '........owlwso',
    '.......owlwso',
    '......owlwso',
    '.....owlwso',
    '....owlwso',
    '...owlsso',
    '...owsso',
    '..oqoo',
    '.oqo',
    '.oo',
  ]),

  // ---- hides and body parts -----------------------------------------------
  leather: S(TINT, [
    '', '', '',
    '..ooo......ooo',
    '..olaoooooolao',
    '...oaallllaaso',
    '...olaaaaaaaso',
    '..olaaaaaaaaaso',
    '..oaaaaaaaaaaso',
    '..oaaaaaaaaasso',
    '...oaaaaaaasdo',
    '...osaaaaassdo',
    '..osdoooooosdo',
    '..ooo......ooo',
  ]),
  rabbit_foot: S({ o: '#3d2a1a', d: '#6b4a2e', s: '#8f6a45', a: '#b08a60', l: '#d4b48c', w: '#f4ead8', p: '#e8b0a8' }, [
    '', '',
    '..........oo',
    '.........osdo',
    '........osado',
    '.......osado',
    '......olasdo',
    '.....olaado',
    '....olaasdo',
    '...owlaado',
    '..owwlaso',
    '.owwwlso',
    '.owwwwso',
    '.owpwwo',
    '..oooo',
  ]),
  spider_eye: S({ o: '#3a0a12', d: '#6e1020', s: '#9a1a2a', a: '#c42c3a', l: '#e25a64', w: '#ffb4b4', k: '#1a0505' }, [
    '', '', '', '',
    '.....oooooo',
    '...ooallllaoo',
    '..oalwwlaaaso',
    '..oalwlakkaso',
    '.oaallakkkaaso',
    '.oaaaaakkaasso',
    '..osaaaaaassdo',
    '..oossaassddo',
    '....ooddddoo',
    '......oooo',
  ]),
  fermented_spider_eye: S({ o: '#2e1208', d: '#5a2a14', s: '#7d3e22', a: '#a3553a', l: '#c87a5c', w: '#e8b49a', k: '#1a0805', m: '#c4a088', M: '#8e6a54', r: '#b22222' }, [
    '', '',
    '.....oooo',
    '....omMmMo',
    '....mrmmrmo',
    '.....oMMo',
    '......oo',
    '...ooallaoo',
    '..oalwlaaaso',
    '.oalwlakkasso',
    '.oaalakkkaaso',
    '.oaaaaakkassdo',
    '..osaaaaassdo',
    '...oossaasddo',
    '.....oooooo',
  ]),
  rotten_flesh: S({ o: '#3a1e14', d: '#5a3424', s: '#7e4a34', a: '#a8644a', l: '#c88466', g: '#6b8a32', G: '#4d6b22', r: '#8a3a2a' }, [
    '', '', '',
    '.....ooooo',
    '...oolllaaoo',
    '..olaagaaraso',
    '..oaaGgaaaaso',
    '.olarraaagaso',
    '.oaaaaaGggaso',
    '.oagaaraaaasdo',
    '.osGgaaaarsdo',
    '..osaaaaassdo',
    '...ossssdddo',
    '....oooooo',
  ]),
  phantom_membrane: S({ o: '#3c3a4e', d: '#5e5b78', s: '#8a86a8', a: '#b2aed0', l: '#d6d3ec', w: '#f2f0ff' }, [
    '',
    '',
    '..oooo',
    '..owllooo',
    '..olaaallooo',
    '..olaaaaaalloo',
    '..oaaasaaaaaaso',
    '...oaasaaaaasso',
    '...oaaasaaassdo',
    '....oaasaaasdo',
    '....oaaasssddo',
    '.....oaso.osdo',
    '.....oso...oo',
    '......o',
  ]),
  shulker_shell: S({ o: '#2e1a35', d: '#4f2d5c', s: '#6e4280', a: '#93619e', l: '#b487bd', w: '#d6b4dc', y: '#d4c48a' }, [
    '', '', '',
    '.....oooooo',
    '...oowllllaoo',
    '..owllaaaaaaso',
    '.owlaaaaaaaasso',
    '.olaaaaaaaaasso',
    '.oaaaaaaaaassdo',
    '.oooooooooooooo',
    '.osssyyyyyysddo',
    '..oddddddddddo',
    '...oooooooooo',
  ]),
  turtle_scute: S({ o: '#1d3a16', d: '#2e5c22', s: '#3f7a2e', a: '#53993d', l: '#78bc5a', w: '#a8dc86' }, [
    '', '', '',
    '.......oo',
    '......owlo',
    '.....owllao',
    '....owlaaaso',
    '...owlaaaaaso',
    '...olaaaaaasso',
    '..owlaaaaaaasdo',
    '..olaaaaaaassdo',
    '..oaaaaaaaassdo',
    '...osssssssddo',
    '....ooooooooo',
  ]),
  armadillo_scute: S({ o: '#4a2a2a', d: '#7a4646', s: '#a0605c', a: '#bf7f78', l: '#dca39a', w: '#f4cdc4' }, [
    '', '', '', '',
    '....oooooooo',
    '...owlllllaao',
    '..owlaaaaaaaso',
    '..olaaoaaoaaso',
    '..olaaoaaoaaso',
    '..oaaaoaaoasso',
    '..osaaoaaoassdo',
    '...ossssssssdo',
    '....ooooooooo',
  ]),
  nautilus_shell: S({ o: '#4a3020', d: '#7a5a42', s: '#b39478', a: '#dcc4a8', l: '#f0e2d0', w: '#ffffff', r: '#c4613e', R: '#94401f' }, [
    '', '', '',
    '.....ooooo',
    '...oowlrllao',
    '..owlrraaraso',
    '..olraooorraso',
    '.owlraolaoraso',
    '.olraoaooraasdo',
    '.olraaooraasdo',
    '.oarrraarraasdo',
    '..osRRRRRsssdo',
    '...oddddddddo',
    '....oooooooo',
  ]),
  honeycomb: S({ o: '#5e3a05', d: '#9a5c0c', s: '#c98414', a: '#e8a823', l: '#f8cd4a', w: '#fff0a0' }, [
    '', '', '',
    '.....oooooo',
    '....owlllldo',
    '...owlaoaaaso',
    '..owlaoaoaasso',
    '..olaoaaaoaaso',
    '..oaaoaoaoaaso',
    '..oaaaoaoaasdo',
    '..osaoaaaoasdo',
    '...osaoaoassdo',
    '....osssssddo',
    '.....oooooo',
  ]),
  ink_sac: S({ o: '#08080e', d: '#16162a', s: '#22223a', a: '#30304e', l: '#4a4a6e', w: '#7a7aa0' }, [
    '', '', '',
    '.......oo',
    '......oaso',
    '.....oo..oo',
    '....oalllaao',
    '...oalwlaaaso',
    '..oalwlaaaaaso',
    '..oalaaaaaasso',
    '..oaaaaaaassdo',
    '..osaaaaassddo',
    '...ossssssddo',
    '....oooooooo',
  ]),

  // ---- dyes (tinted) ------------------------------------------------------
  dye: S(TINT, [
    '', '', '',
    '.......oo',
    '......owlo',
    '.....owwlao',
    '.....owlaao',
    '....owlaaaso',
    '...owlaaaaaso',
    '...olaaaaaaso',
    '..owlaaaaaasdo',
    '..olaaaaaassdo',
    '..oaaaaaassddo',
    '...osssssdddo',
    '....oooooooo',
  ]),

  // secondary (mixed) dyes: a round pile
  dye_round: S(TINT, [
    '', '', '',
    '......oooo',
    '....oowlllaoo',
    '...owllaaaaaso',
    '..owlaaaaaaasdo',
    '..olaaaaaaaasdo',
    '..olaaaaaaassdo',
    '..oaaaaaaaassdo',
    '..osaaaaassssdo',
    '...osssssssddo',
    '....odddddddo',
    '.....ooooooo',
  ]),
  // white dye: a low heap of powder
  dye_powder: S(TINT, [
    '', '', '', '', '',
    '.......ooo',
    '.....oowlaoo',
    '....owlaaaaso',
    '...owlaaaaaasoo',
    '..owlaaaaaaaasdo',
    '.owlaaaaaaaaasdo',
    '.oaaaaaaaaaassdo',
    '.ossssssssssddo',
    '..oooooooooooo',
  ]),
  // black, blue and brown dye: an irregular two-lobed lump
  dye_lump: S(TINT, [
    '', '', '',
    '...oooo',
    '..owwlao.oooo',
    '..owllaaoolaso',
    '..olllaaaaaasdo',
    '.oollaaaaaassdo',
    '.olaaaaaaaassdo',
    '.olaaaaaaasssdo',
    '.oaaaaaaassssdo',
    '.osaaaaasssddo',
    '..ossssssdddo',
    '...oddddddoo',
    '....oooooo',
  ]),

  end_crystal: S({ g: '#e6d8f2', G: '#c9b4e6c0', i: '#d8c8f050', c: '#f27ae6', C: '#c43cc8', D: '#7a1890', w: '#ffe0ff' }, [
    '',
    '.......gg',
    '.....ggiigg',
    '...ggiiiiiigg',
    '.ggiiiiiiiiiigg',
    '.gGGiiicCiiiGGg',
    '.giiGGccCCGGiig',
    '.giiiccwwCCiiig',
    '.giiiCCwwDDiiig',
    '.giiiiCCDDiiiig',
    '.giiiiiCDiiiiig',
    '.ggiiiiGGiiiigg',
    '...ggiiGGiigg',
    '.....ggGGgg',
    '.......gg',
  ]),

  // ---- tablets, sherds, papers --------------------------------------------
  smithing_template: S(TINT2, [
    '', '',
    '...oooooooooo',
    '..owllllllllao',
    '..olaaaaaaaaso',
    '..olaaafgaaaso',
    '..olaafEEgaaso',
    '..olafEaaEgaso',
    '..olafEaaEeaso',
    '..olafEaaEeaso',
    '..olaafEEeaaso',
    '..olaaaeeaaaso',
    '..olaaaaaaaaso',
    '..oassssssssdo',
    '...oooooooooo',
  ]),
  pottery_sherd: S(TINT2, SHERD_ROWS),
  paper: S({ o: '#6e6650', d: '#a8a088', s: '#cfc8b0', a: '#e8e2cc', l: '#f6f2e4', w: '#ffffff' }, [
    '', '',
    '....ooooooooo',
    '...owwwwwwwwlo',
    '...owlllllllao',
    '..owlllllllaso',
    '..owssssssslao',
    '..owlllllllaso',
    '..owlllllllao',
    '.owsssssssslao',
    '.owlllllllaaso',
    '.owlllllllaso',
    '.osaaaaaaaaso',
    '..odssssssddo',
    '...ooooooooo',
  ]),
  banner_pattern: S({ ...TINT, x: '%1', X: '%3' }, [
    '', '',
    '....ooooooooo',
    '...owwwwwwwwlo',
    '...owlllxllllao',
    '..owllxXxllaso',
    '..owlxXlXxlaso',
    '..owllxXxllaso',
    '..owlllxllllao',
    '.owlllxlxlllao',
    '.owllxlllxlaso',
    '.owlllllllaso',
    '.osaaaaaaaaso',
    '..odssssssddo',
    '...ooooooooo',
  ]),
  map: S({ o: '#5a4a32', d: '#8a7656', s: '#b8a47e', a: '#d8c9a0', l: '#ebe0bf', w: '#f8f2dc', x: '#a08c66' }, [
    '', '',
    '..oooooooooooo',
    '..owwwwwwwwwlo',
    '..owllllllllao',
    '..owlxxlllllao',
    '..owlllllxllao',
    '..owllllllllao',
    '..owllxllllxao',
    '..owlllllllaao',
    '..owlllxllllao',
    '..owllllllllao',
    '..olaaaaaaaaso',
    '..oooooooooooo',
  ]),
  filled_map: S({ o: '#5a4a32', s: '#b8a47e', a: '#d8c9a0', l: '#ebe0bf', w: '#f8f2dc', g: '#7aa04a', G: '#5c8236', b: '#5a86c4', B: '#3f6aa8', r: '#c43a2a' }, [
    '', '',
    '..oooooooooooo',
    '..owwwwwwwwwlo',
    '..owbbbggGgbao',
    '..owbBggggGbao',
    '..owbgggrgggao',
    '..owggGgggbbao',
    '..owgggggbBbao',
    '..owbggGgbbbao',
    '..owbbgggbbbao',
    '..owbbbggbbbao',
    '..olaaaaaaaaso',
    '..oooooooooooo',
  ]),

  // ---- books --------------------------------------------------------------
  book: S(BOOK_PAL, BOOK_ROWS),
  enchanted_book: S({ ...BOOK_PAL, o: '#1e0a28', C: '#6a2a8a', L: '#9a5ac0', D: '#47185e', t: '#e8c45a' }, BOOK_ROWS.map((r, y) => (y >= 4 && y <= 9 ? r.replace(/C/g, (c, x) => ((x + y) % 5 === 0 ? 't' : c)) : r))),
  knowledge_book: S({ ...BOOK_PAL, o: '#2a0a0a', C: '#a02020', L: '#cc4040', D: '#701010', t: '#f2c14e' }, BOOK_ROWS.map((r, y) => (y === 5 || y === 9 ? r.replace(/C{4}$/, 'tttt').replace(/CCCCD/, 'ttttD') : r))),
  writable_book: S({ ...BOOK_PAL, f: '#ffffff', F: '#c8c8c8', k: '#1a1a1a' }, [
    '',
    '...........kf',
    '....ooooooFkf',
    '...oLLLLLLFkfo',
    '..oLCCCCCFkfDo',
    '..oLCCCCFkfCDo',
    '..oLCCCFkfCCDo',
    '..oLCCFkfCCCDo',
    '..oLCFkfCCCCDo',
    '..oLCkkCCCCCDo',
    '..oLCkCCCCCCDo',
    '..oLCCCCCCCDDo',
    '..oLDDDDDDDDDpo',
    '..oopppppppppPo',
    '...oPPPPPPPPPo',
    '....ooooooooo',
  ]),
  written_book: S({ ...BOOK_PAL, C: '#6e4a2a', L: '#8e6a44', D: '#4e3018', t: '#d8c060', x: '#2a1a0e' }, [
    '',
    '',
    '....oooooooooo',
    '...oLLLLLLLLLCo',
    '..oLCCCCCCCCCDo',
    '..oLCxxxxxxCCDo',
    '..oLCCCCCCCCCDo',
    '..oLCxxxxxCCCDo',
    '..oLCCCCCCCCCDo',
    '..oLCxxxxxxCCDo',
    '..oLCCCCCCCCCDo',
    '..oLCCCCCCCCDDo',
    '..oLDDDDDDDDDpo',
    '..oopppppppppPo',
    '...oPPPPPPPPPo',
    '....ooooooooo',
  ]),

  // ---- bottles ------------------------------------------------------------
  potion: S({ ...GLASS, l: '@5', a: '@3', s: '@2', d: '@1' }, BOTTLE_ROWS),
  splash_potion: S({ ...GLASS, l: '@5', a: '@3', s: '@2', d: '@1' }, SPLASH_ROWS),
  glass_bottle: S({ ...GLASS, l: '#ffffff80', a: '#ffffff18', s: '#d8eef5', d: '#9fc2cf' }, BOTTLE_ROWS.map((r, y) => (y >= 8 && y <= 12 ? r.replace(/a/g, (c, x) => (x === 10 && y <= 10 ? 'l' : '.')).replace(/s/g, (c, x) => (x === 11 && y >= 11 ? 's' : '.')) : r))),
  experience_bottle: S({ ...GLASS, l: '#f8ffc0', a: '#b8e64a', s: '#6fbf2a', d: '#3f8a1a', y: '#ffffff' }, BOTTLE_ROWS.map((r, y) => (y === 9 ? r.replace('aaaa', 'ayaa') : y === 11 ? r.replace('aaaa', 'aaya') : r))),
  ominous_bottle: S({ ...GLASS, g: '#1c2620', G: '#4a5e52', c: '#3c3c3c', C: '#1e1e1e', l: '#c0e8c8', a: '#3e6a4c', s: '#2a4a36', d: '#1a3022', k: '#0a120c' }, BOTTLE_ROWS.map((r, y) => (y === 9 ? r.replace('aaaaaa', 'akaaka') : y === 11 ? r.replace('aaaaa', 'akkka') : r))),

  // ---- discs --------------------------------------------------------------
  music_disc: S({ o: '#0c0c0c', k: '#232323', K: '#191919', h: '#4c4c4c', a: '@3', A: '@2', x: '#050505' }, [
    '', '',
    '.....oooooo',
    '...ookkhhkkoo',
    '..okkhkkkkkkko',
    '..okhkkkkkkkko',
    '.okhkkaaaakkkko',
    '.okkkkaxxAkkkko',
    '.okkkkaxxAkkKko',
    '.okkkkAAAAkkKko',
    '..okkkkkkkKKko',
    '..okkkkkkKKkko',
    '...ookkKKkkoo',
    '.....oooooo',
  ]),
  disc_fragment: S({ o: '#0c0c0c', k: '#232323', h: '#4c4c4c', a: '#2fa59a' }, [
    '', '', '',
    '......ooooo',
    '.....okkhhko',
    '....okhkkkko',
    '...okhkkkako',
    '...okkkkaako',
    '..okkkkkako',
    '..okkkkkko',
    '.okkkkkko',
    '.okkkkoo',
    '.ookoo',
    '..oo',
  ]),
};

for (const [k, glyph] of Object.entries(SHERD_GLYPHS)) sprites[`${k}_pottery_sherd`] = S(TINT2, sherd(glyph));

sprites.glow_ink_sac = S({ o: '#062a2a', d: '#0c4a48', s: '#14706a', a: '#1fa094', l: '#5ae0c8', w: '#c8fff0' }, sprites.ink_sac.rows);

// music disc label colours
const DISCS = {
  13: '#e8c03a', cat: '#5cc23a', blocks: '#e05a2a', chirp: '#c42a2a', far: '#a8d870', mall: '#7a5ac8', mellohi: '#d8a0d8',
  stal: '#2a2a2a', strad: '#f0f0f0', ward: '#3a7a3a', 11: '#606060', wait: '#3ab0c8', pigstep: '#d06a3a', otherside: '#3a8ad0',
  5: '#2a5a5a', relic: '#3aa8a0', creator: '#e8c060', creator_music_box: '#c8a050', precipice: '#b07a50', tears: '#b8d8f0', lava_chicken: '#f0a030',
};
const TRIMS = {
  netherite_upgrade: '#4a3e40', sentry: '#8a8a8a', vex: '#9c9c9c', wild: '#6d7a45', coast: '#5f8e8b', dune: '#d4c286', wayfinder: '#a5664a',
  raiser: '#a86a4e', shaper: '#9c6248', host: '#a87a5e', ward: '#3c3c46', silence: '#2a2a32', tide: '#5aa59c', snout: '#2f2a30',
  rib: '#5a2228', eye: '#d8daa0', spire: '#a77aa7', flow: '#8f7ac0', bolt: '#b5734c',
};
const SHERD_TINT = { a: ['#3a1a0e', '#6a3220', '#8e4a30', '#a8603e', '#c07a54', '#d89a74'], b: '#4a2214' };
const hashHue = s => { let h = 0; for (const ch of s) h = (h * 31 + ch.charCodeAt(0)) >>> 0; return `hsl(${h % 360} 55% 50%)`; };

export const rules = [
  [/^(iron|gold|copper|netherite)_ingot$/, 'ingot', (n, m) => (m[1] === 'netherite'
    ? ['#120e0f', '#2a2223', '#3c3335', '#4e4446', '#655a5c', '#8a7e80']
    : m[1] === 'copper' ? ['#3d1a10', '#8a3e22', '#b4572f', '#d47a4e', '#ec9a6c', '#ffcfb0'] : m[1])],
  [/^(iron|gold|copper)_nugget$/, 'nugget', (n, m) => (m[1] === 'copper' ? 'copper' : m[1])],
  [/^raw_(iron|gold|copper)$/, 'raw', (n, m) => ({
    iron: ['#3d2f25', '#6b5241', '#94775f', '#c2a283', '#d8bc9f', '#efdcc8'],
    gold: ['#52290a', '#a35c0e', '#d48e17', '#f0bd2a', '#fadc5a', '#fff4a8'],
    copper: ['#40190f', '#7c3a22', '#a8512f', '#c96f45', '#e48d5e', '#f8b88e'],
  })[m[1]]],
  [/^netherite_scrap$/, 'netherite_scrap', { a: ['#1a1112', '#33282a', '#4a3b3c', '#5e4d4c', '#76625e', '#9a847c'], b: ['#2a1510', '#4a2418', '#7a4a3a', '#8a5a48', '#9c6a56', '#b08070'] }],
  [/^diamond$/, 'diamond', 'diamond'],
  [/^emerald$/, 'emerald', 'emerald'],
  [/^lapis_lazuli$/, 'lapis', 'lapis'],
  [/^quartz$/, 'quartz', ['#5e4a44', '#a8928a', '#cdbcb4', '#e6dcd4', '#f4eee8', '#ffffff']],
  [/^amethyst_shard$/, 'amethyst_shard', 'amethyst'],
  [/^echo_shard$/, 'echo_shard'],
  [/^prismarine_shard$/, 'prismarine_shard'],
  [/^prismarine_crystals$/, 'prismarine_crystals'],
  [/^nether_star$/, 'nether_star', { glint: true }],
  [/^coal$/, 'lump', ['#050505', '#141414', '#202020', '#2e2e2e', '#565656', '#8a8a8a']],
  [/^charcoal$/, 'lump', ['#0e0a06', '#1f1810', '#2e251a', '#403427', '#5a4b3a', '#7e6c58']],
  [/^redstone$/, 'dust', ['#2a0000', '#5e0000', '#8e0000', '#c80000', '#ff2a1a', '#ff9a8a']],
  [/^glowstone_dust$/, 'dust', ['#5a3a10', '#9a6a20', '#c89838', '#ecc85a', '#fbe78a', '#ffffd0']],
  [/^gunpowder$/, 'dust', ['#1e1e1e', '#3a3a3a', '#525252', '#6e6e6e', '#8e8e8e', '#bdbdbd']],
  [/^sugar$/, 'dust', ['#8a96a8', '#b8c4d4', '#d4dce8', '#ebf0f6', '#f8fbff', '#ffffff']],
  [/^blaze_powder$/, 'dust', ['#5a1e00', '#a04000', '#d86a00', '#f89a10', '#ffcf40', '#fff6a0']],
  [/^bone_meal$/, 'dust', ['#6a6a78', '#a4a4b0', '#c8c8d2', '#e2e2ea', '#f2f2f8', '#ffffff']],
  [/^stick$/, 'stick'],
  [/^debug_stick$/, 'stick', { glint: true }],
  [/^(end|ender)_crystal$/, 'end_crystal'],
  [/^blaze_rod$/, 'rod', ['#6a2a00', '#c26000', '#f09a00', '#ffc81a', '#fff05a', '#ffffc0']],
  [/^breeze_rod$/, 'breeze_rod'],
  [/^bone$/, 'bone'],
  [/^string$/, 'string'],
  [/^feather$/, 'feather'],
  [/^leather$/, 'leather', 'leather'],
  [/^rabbit_hide$/, 'leather', ['#3a2a1c', '#6e5038', '#8f6e50', '#b08d6b', '#c9a888', '#e0c6a8']],
  [/^rabbit_foot$/, 'rabbit_foot'],
  [/^flint$/, 'flint', ['#0e0e0e', '#222222', '#343434', '#484848', '#666666', '#959595']],
  [/^ghast_tear$/, 'ghast_tear'],
  [/^magma_cream$/, 'magma_cream'],
  [/^slime_ball$/, 'slime_ball'],
  [/^clay_ball$/, 'ball', ['#4a4e5a', '#737886', '#8d93a2', '#a4aab8', '#bcc2ce', '#dce0e8']],
  [/^resin_clump$/, 'ball', ['#4a1e00', '#8a3e05', '#c26010', '#e88420', '#f8ac40', '#ffdc8a']],
  [/^(brick|nether_brick|resin_brick)$/, 'ingot', (n, m) => ({
    brick: ['#3a1408', '#6a2a16', '#8e3c22', '#b0533a', '#c86e52', '#de9078'],
    nether_brick: ['#120507', '#260b10', '#3a1219', '#4e1c24', '#662a34', '#80404a'],
    resin_brick: ['#4a1c00', '#8a3a05', '#b8540e', '#de7a1c', '#f49c38', '#ffc878'],
  })[m[1]]],
  [/^shulker_shell$/, 'shulker_shell'],
  [/^phantom_membrane$/, 'phantom_membrane'],
  [/^turtle_scute$/, 'turtle_scute'],
  [/^armadillo_scute$/, 'armadillo_scute'],
  [/^nautilus_shell$/, 'nautilus_shell'],
  [/^heart_of_the_sea$/, 'heart_of_the_sea'],
  [/^honeycomb$/, 'honeycomb'],
  [/^ink_sac$/, 'ink_sac'],
  [/^glow_ink_sac$/, 'glow_ink_sac'],
  [/^heavy_core$/, 'heavy_core'],
  [/^spider_eye$/, 'spider_eye'],
  [/^fermented_spider_eye$/, 'fermented_spider_eye'],
  [/^rotten_flesh$/, 'rotten_flesh'],
  [/^(black|blue|brown)_dye$/, 'dye_lump', (n, m) => DYES[m[1]]],
  [/^white_dye$/, 'dye_powder', DYES.white],
  [/^(lime|cyan|purple|magenta|pink|light_blue|gray|light_gray|silver)_dye$/, 'dye_round', (n, m) => DYES[m[1]]],
  [/^(\w+)_dye$/, 'dye', (n, m) => DYES[m[1]] || DYES[dyeOf(n)] || hashHue(n)],
  [/^(netherite_upgrade|\w+_armor_trim)_smithing_template$/, 'smithing_template', (n, m) => {
    const c = TRIMS[m[1].replace(/_armor_trim$/, '')] || '#7a7a7a';
    return { a: c, b: m[1] === 'netherite_upgrade' ? '#8a4a3a' : c };
  }],
  ...Object.keys(SHERD_GLYPHS).map(k => [new RegExp(`^${k}_pottery_sherd$`), `${k}_pottery_sherd`, SHERD_TINT]),
  [/^(?:\w+_)?pottery_sherd$/, 'pottery_sherd', SHERD_TINT],
  [/^\w+_banner_pattern$/, 'banner_pattern', { a: 'paper', b: '#7a4a2a' }],
  [/^paper$/, 'paper'],
  [/^(map|empty_map)$/, 'map'],
  [/^filled_map$/, 'filled_map'],
  [/^book$/, 'book'],
  [/^enchanted_book$/, 'enchanted_book', { glint: true }],
  [/^knowledge_book$/, 'knowledge_book'],
  [/^writable_book$/, 'writable_book'],
  [/^written_book$/, 'written_book'],
  [/^potion$/, 'potion', '#e8366e'],
  [/^(splash|lingering)_potion$/, 'splash_potion', (n, m) => (m[1] === 'lingering' ? '#b84ac8' : '#e8366e')],
  [/^glass_bottle$/, 'glass_bottle'],
  [/^honey_bottle$/, 'potion', ['#6a3a00', '#b06a05', '#de9410', '#f6b425', '#fcd35a', '#fff0b0']],
  [/^dragon_breath$/, 'potion', '#d06ac8'],
  [/^experience_bottle$/, 'experience_bottle', { glint: true }],
  [/^ominous_bottle$/, 'ominous_bottle'],
  [/^music_disc_(\w+)$/, 'music_disc', (n, m) => DISCS[m[1]] || hashHue(m[1])],
  [/^disc_fragment(_\w+)?$/, 'disc_fragment'],
];
