// Item sprites: tools, weapons and handheld gadgets. See draw.js for the format.
// Tool heads use the material ramp: 0 outline · 1 dark · 2 shade · 3 base · 4 light · 5 glint.
// Handles are stick brown: k outline · H shade · h light.

const STICK = { k: '#28190a', H: '#493615', h: '#896727', g: '#684e1e' };
const MAT = { 0: '@0', 1: '@1', 2: '@2', 3: '@3', 4: '@4', 5: '@5' };
const TOOL = { ...MAT, ...STICK };

export const sprites = {
  sword: {
    pal: TOOL,
    rows: [
      '................',
      '.............000',
      '............0530',
      '...........05320',
      '..........05320.',
      '....k....05320..',
      '...khk..05320...',
      '....khk05320....',
      '.....kh5320.....',
      '......kh00......',
      '.....kHkhk......',
      '....kHk.khk.....',
      '...kHk...k......',
      '..kHk...........',
      '.khHk...........',
      '.kkk............',
    ],
  },
  pickaxe: {
    pal: TOOL,
    rows: [
      '................',
      '...0000000000...',
      '..055555544330..',
      '...003322233330.',
      '.....0000.kh330.',
      '.........khH230.',
      '........khH.230.',
      '.......khH.0230.',
      '......khH..0230.',
      '.....khH...0220.',
      '....khH....0220.',
      '...khH......020.',
      '..khH.......010.',
      '.khH.........0..',
      '.kH.............',
      '................',
    ],
  },
  axe: {
    pal: TOOL,
    rows: [
      '................',
      '....00000....khH',
      '...05544430.khH.',
      '..054444333khH..',
      '..05443332khH...',
      '..0543322khH....',
      '..043222khH.....',
      '...0221khH......',
      '....00khH.......',
      '.....khH........',
      '....khH.........',
      '...khH..........',
      '..khH...........',
      '.khH............',
      '.kH.............',
      '................',
    ],
  },
  shovel: {
    pal: TOOL,
    rows: [
      '...........000..',
      '..........05540.',
      '.........0554430',
      '........05544430',
      '.......054443320',
      '.......04433220.',
      '........033220..',
      '.......khH00....',
      '......khH.......',
      '.....khH........',
      '....khH.........',
      '...khH..........',
      '..khH...........',
      '.khH............',
      '.kH.............',
      '................',
    ],
  },
  hoe: {
    pal: TOOL,
    rows: [
      '................',
      '....00000000....',
      '...0555544430...',
      '...03320002khH..',
      '...0220...khH...',
      '....00...khH....',
      '........khH.....',
      '.......khH......',
      '......khH.......',
      '.....khH........',
      '....khH.........',
      '...khH..........',
      '..khH...........',
      '.khH............',
      '.kH.............',
      '................',
    ],
  },
  spear: {
    pal: TOOL,
    rows: [
      '.............000',
      '............0540',
      '...........05430',
      '..........054320',
      '..........03220.',
      '.........0110...',
      '........khH.....',
      '.......khH......',
      '......khH.......',
      '.....khH........',
      '....khH.........',
      '...khH..........',
      '..khH...........',
      '.khH............',
      '.kH.............',
      '................',
    ],
  },
  mace: {
    pal: { ...STICK, o: '#1f1f24', d: '#3d3d46', m: '#5d5e69', l: '#8a8c98', w: '#b9bcc8', r: '#6e5a3c', R: '#4a3a26' },
    rows: [
      '.........o..o...',
      '........ooooooo.',
      '.......owwllmmo.',
      '......owllmmmdo.',
      '......olmmmmddo.',
      '.....oolmmmddoo.',
      '......omddddo...',
      '......kRooooo...',
      '.....krR........',
      '....krR.........',
      '...krR..........',
      '..krR...........',
      '.kRRk...........',
      '.kkk............',
      '................',
      '................',
    ],
  },
  trident: {
    pal: { o: '#17302d', s: '#4f8b82', S: '#2f5a54', d: '#3c7a70', l: '#9fe0d3', L: '#6cc0b1' },
    rows: [
      '................',
      '..........l...l.',
      '.........L...L..',
      '........d...L...',
      '.........d.L....',
      '..........d...l.',
      '.........sSd.L..',
      '........sS..d...',
      '.......sS.......',
      '......sS........',
      '.....sS.........',
      '....sS..........',
      '...sS...........',
      '..sS............',
      '.sS.............',
      '.o..............',
    ],
  },
  bow: {
    pal: { o: '#28190a', w: '#896727', W: '#5a4220', s: '#d8d8d8' },
    rows: [
      '................',
      '..ooooo.........',
      '.owwwwwoo.......',
      '..osWWWwwooo....',
      '....s..WWwwwo...',
      '.....s...WWwo...',
      '......s...Wwo...',
      '.......s...Wwo..',
      '........s..Wwo..',
      '.........s..Wwo.',
      '..........s.Wwo.',
      '...........sWwo.',
      '............swo.',
      '............owo.',
      '.............o..',
      '................',
    ],
  },
  crossbow: {
    pal: { ...STICK, m: '#b4b4b4', M: '#6e6e6e', s: '#e8e8e8' },
    rows: [
      '.....kk.........',
      '....kMmk........',
      '....skMmk.......',
      '....s.kMmk.khH..',
      '....s..kMmkhH...',
      '.....s...khH....',
      '.....s..khHMmk..',
      '......skhH.kMmk.',
      '......khH...kMmk',
      '.....khH.....kMk',
      '....khHssssssk..',
      '...khH..........',
      '..khH...........',
      '.khH............',
      '.kH.............',
      '................',
    ],
  },
  arrow: {
    pal: { g: '%5', G: '%3', x: '%1', w: '#896727', f: '@4', F: '@2' },
    rows: [
      '................',
      '............xxx.',
      '...........xggx.',
      '...........wgGx.',
      '..........w.xxx.',
      '.........w......',
      '........w.......',
      '.......w........',
      '......w.........',
      '.....w..........',
      '...fwF..........',
      '..fwF...........',
      '.fwF............',
      'fwF.............',
      '.F..............',
      '................',
    ],
  },
  shield: {
    pal: { o: '#1e1e1e', m: '#9a9a9a', M: '#5c5c5c', w: '#9f844d', W: '#6b5530', d: '#7d6538' },
    rows: [
      '..oooooooooooo..',
      '..omMMMMMMMMmo..',
      '..oMwwWwwwWwMo..',
      '..oMwwWwwwWwMo..',
      '..oMwdWwwdWwMo..',
      '..oMwwWwwwWwMo..',
      '..oMwwWwwwWwMo..',
      '..oMwwWdwwWwMo..',
      '..oMwwWwwwWwMo..',
      '..oMwwWwwwWdMo..',
      '..oMwwWwwwWwMo..',
      '...oMwWwwwWMo...',
      '...oMwWwwdWMo...',
      '....oMWwwWMo....',
      '.....oMMMMo.....',
      '......oooo......',
    ],
  },
  fishing_rod: {
    pal: { ...STICK, s: '#d8d8d8', m: '#9a9a9a' },
    rows: [
      '.............kk.',
      '............khHs',
      '...........khH.s',
      '..........khH..s',
      '.........khH...s',
      '........khH....s',
      '.......khH.....s',
      '......khH......s',
      '.....khH.......s',
      '....khH........s',
      '...khH.........s',
      '..khH.........ms',
      '.khH..........m.',
      'khH............m',
      'kH.............m',
      '..............m.',
    ],
  },
  carrot_on_a_stick: {
    pal: { ...STICK, s: '#d8d8d8', c: '#f08a24', C: '#b65a0e', x: '#5a2a05', l: '#5ea832', L: '#2f6b1a' },
    rows: [
      '.............kk.',
      '............khHs',
      '...........khH.s',
      '..........khH..s',
      '.........khH...s',
      '........khH....s',
      '.......khH.....s',
      '......khH......s',
      '.....khH......Ll',
      '....khH......lLL',
      '...khH......xccx',
      '..khH.......xcCx',
      '.khH.........cCx',
      'khH..........xCx',
      'kH............x.',
      '................',
    ],
  },
  warped_fungus_on_a_stick: {
    pal: { ...STICK, s: '#d8d8d8', t: '#14b485', T: '#0d7a5c', x: '#08392b', e: '#d06a2a', y: '#7a5c45' },
    rows: [
      '.............kk.',
      '............khHs',
      '...........khH.s',
      '..........khH..s',
      '.........khH...s',
      '........khH....s',
      '.......khH.....s',
      '......khH......s',
      '.....khH.....xxs',
      '....khH.....xtTx',
      '...khH.....xtetx',
      '..khH......xTTTx',
      '.khH........xyx.',
      'khH..........y..',
      'kH...........y..',
      '................',
    ],
  },
  shears: {
    pal: { o: '#262626', l: '#e8e8e8', m: '#a8a8a8', d: '#7a7a7a' },
    rows: [
      '................',
      '............oo..',
      '...........olmo.',
      '..........olmo..',
      '.........olmo...',
      '........olmo....',
      '..ooo..olmo.....',
      '.odddoolmo......',
      '.od.dddddo......',
      '.odddoddo.......',
      '..ooo.odo.......',
      '.....odddo......',
      '.....od.do......',
      '.....odddo......',
      '......ooo.......',
      '................',
    ],
  },
  flint_and_steel: {
    pal: { o: '#262626', l: '#dcdcdc', m: '#a8a8a8', d: '#6a6a6a', f: '#5a5a5a', F: '#3a3a3a', w: '#8a8a8a' },
    rows: [
      '................',
      '...oooooo.......',
      '..olllllmo......',
      '..olmmmmdo......',
      '..olo..odo......',
      '..olo..odo......',
      '..olo..odo......',
      '..omo...o.......',
      '...o.....ooo....',
      '........owffo...',
      '.......owfffFo..',
      '......owffffFo..',
      '......offfffFo..',
      '.......oFfFFo...',
      '........oooo....',
      '................',
    ],
  },
  brush: {
    pal: { ...STICK, o: '#3b2a1a', b: '#e9dcc0', B: '#c4ac85', c: '#c76b46', C: '#7d3a24' },
    rows: [
      '...........oo...',
      '..........obbo..',
      '.........obbBBo.',
      '........obbBBBo.',
      '........obBBBo..',
      '.........cCBo...',
      '........cCCo....',
      '.......khH......',
      '......khH.......',
      '.....khH........',
      '....khH.........',
      '...khH..........',
      '..khH...........',
      '.khH............',
      '.kH.............',
      '................',
    ],
  },
  spyglass: {
    pal: { o: '#3d1a10', c: '#e7865f', C: '#a4502f', d: '#7d3a24', l: '#c6efff', L: '#7fb8d0', r: '#4a3020' },
    rows: [
      '................',
      '...........ooo..',
      '..........olLlo.',
      '.........olLLLo.',
      '........ocLLLo..',
      '.......occCoo...',
      '......occCdo....',
      '.....ooccdo.....',
      '....orrocdo.....',
      '...occCrro......',
      '..occCdo........',
      '.occCdo.........',
      '.occdo..........',
      '..ooo...........',
      '................',
      '................',
    ],
  },
  compass: {
    pal: { o: '#2b2b2b', f: '#a8a8a8', F: '#6e6e6e', l: '#d8d8d8', d: '#3d3d3d', D: '#262626', r: '#e2352c', w: '#e8e8e8' },
    rows: [
      '................',
      '.....oooooo.....',
      '...oollllllfoo..',
      '..olfddDDddFfo..',
      '..olddDDDDdddFo.',
      '.olfdDDDDDrddFo.',
      '.oldDDDDDrdDddFo',
      '.olDDDDDrDDDDdFo',
      '.olDDDDwDDDDDdFo',
      '.oldDDwDDDDDddFo',
      '.ofddwDDDDDddFo.',
      '..ofddDDDDddFFo.',
      '..oFfddddddFFo..',
      '...ooFFFFFFoo...',
      '.....oooooo.....',
      '................',
    ],
  },
  recovery_compass: {
    pal: { o: '#0e2a2a', f: '#4fa39c', F: '#2c6b66', l: '#8adbd2', d: '#1b3a40', D: '#0f2328', r: '#5ff0e0', w: '#2f8a86' },
    rows: [
      '................',
      '.....oooooo.....',
      '...oollllllfoo..',
      '..olfddDDddFfo..',
      '..olddDDDDdddFo.',
      '.olfdDDDDDrddFo.',
      '.oldDDDDDrdDddFo',
      '.olDDDDDrDDDDdFo',
      '.olDDDDwDDDDDdFo',
      '.oldDDwDDDDDddFo',
      '.ofddwDDDDDddFo.',
      '..ofddDDDDddFFo.',
      '..oFfddddddFFo..',
      '...ooFFFFFFoo...',
      '.....oooooo.....',
      '................',
    ],
  },
  clock: {
    pal: { o: '#502a07', f: '#fcee4b', F: '#dc9613', G: '#b26411', b: '#4a8ad8', B: '#2f63a8', y: '#ffe25a', n: '#1d2140', N: '#2b3060', h: '#404040' },
    rows: [
      '................',
      '.....oooooo.....',
      '...ooffffffoo...',
      '..offbbbbbbFFo..',
      '..ofbbbyybbbFo..',
      '.ofbbbyyyybbBFo.',
      '.ofbbbbyybbbBFo.',
      '.ofbbbbhbbbbBFo.',
      '.ofNNNNhNNNNNFo.',
      '.ofNnnnnnnnnNFo.',
      '.oFNnnnnnnnNNGo.',
      '..oFNnnnnnNNGo..',
      '..oFFNNNNNNGGo..',
      '...ooGGGGGGoo...',
      '.....oooooo.....',
      '................',
    ],
  },
  goat_horn: {
    pal: { o: '#3a3328', l: '#e6dcc2', m: '#c4b796', d: '#8e8066', r: '#6a5e48' },
    rows: [
      '................',
      '............oo..',
      '...........olmo.',
      '..........olmdo.',
      '..........omdo..',
      '.........olrdo..',
      '........olmdo...',
      '.......olmrdo...',
      '......olmmdo....',
      '....oolmmrdo....',
      '..oolmmmddo.....',
      '.olmmmrddoo.....',
      '.olmddddo.......',
      '..oooooo........',
      '................',
      '................',
    ],
  },
  key: {
    pal: { o: '@0', d: '@1', m: '@2', b: '@3', l: '@4', w: '@5', c: '%3', C: '%1' },
    rows: [
      '................',
      '.........oooo...',
      '........olllbo..',
      '.......olbbbbmo.',
      '.......olboobmo.',
      '.......obbo.bmo.',
      '.......odbbbmmo.',
      '......olodmmmo..',
      '.....olmooooo...',
      '....olmo........',
      '...olmo.........',
      '..occo..........',
      '.occCco.........',
      '..oCco..........',
      '...oo...........',
      '................',
    ],
  },
  wind_charge: {
    pal: { o: '#3c4a78', d: '#6e82c0', m: '#a6b8ec', l: '#d8e4ff', w: '#ffffff' },
    rows: [
      '................',
      '................',
      '.....oooooo.....',
      '....odmmmmdo....',
      '...odmllllmdo...',
      '...omlwwwwldo...',
      '..odmlwddwlmdo..',
      '..omlwdmmdwlmo..',
      '..omlwdmmdwlmo..',
      '..odmlwddwlmdo..',
      '...omlwwwwldo...',
      '...odmllllmdo...',
      '....odmmmmdo....',
      '.....oooooo.....',
      '................',
      '................',
    ],
  },
  fire_charge: {
    pal: { o: '#1a0e08', d: '#3a2418', m: '#5a3a26', r: '#c8401a', y: '#f5a623', w: '#ffe36a' },
    rows: [
      '................',
      '................',
      '.....oooooo.....',
      '....odmmddmo....',
      '...odmryrmddo...',
      '...omrywyrmdo...',
      '..odmryyyrdmdo..',
      '..omdmrrrmdrmo..',
      '..omrrdmmdryro..',
      '..odyyrdmdrydo..',
      '...omrydmdrmo...',
      '...odmmdmmmdo...',
      '....oddmmddo....',
      '.....oooooo.....',
      '................',
      '................',
    ],
  },
  snowball: {
    pal: { o: '#5f7590', d: '#b8cde0', m: '#dce9f5', l: '#f6fbff', w: '#ffffff' },
    rows: [
      '................',
      '................',
      '................',
      '......oooo......',
      '.....owwlmo.....',
      '....owwllmdo....',
      '...owllllmmdo...',
      '...owlllmmmdo...',
      '...olllmmmddo...',
      '...olmmmmmddo...',
      '....ommmmddo....',
      '.....oddddo.....',
      '......oooo......',
      '................',
      '................',
      '................',
    ],
  },
  egg: {
    pal: { o: '%0', d: '@2', m: '@3', l: '@4', w: '@5', s: '%2' },
    rows: [
      '................',
      '................',
      '......oooo......',
      '.....olwlmo.....',
      '....olwllmmo....',
      '....owllmsmo....',
      '...olllmmmmdo...',
      '...olsllmmmdo...',
      '...ollmmmsmdo...',
      '...olmmmmmmdo...',
      '...omsmmmmddo...',
      '....ommmsddo....',
      '.....oddddo.....',
      '......oooo......',
      '................',
      '................',
    ],
  },
  ender_pearl: {
    pal: { o: '#08201c', d: '#0f3d36', m: '#1b6b5e', l: '#2f9c86', w: '#7fe0c8', W: '#c8fff0' },
    rows: [
      '................',
      '................',
      '................',
      '......oooo......',
      '.....ommmmo.....',
      '....omlwwlmo....',
      '...omlwWwllmo...',
      '...omlwwllmdo...',
      '...omllllmmdo...',
      '...ommllmmddo...',
      '....ommmmddo....',
      '.....oddddo.....',
      '......oooo......',
      '................',
      '................',
      '................',
    ],
  },
  ender_eye: {
    pal: { o: '#0a2a14', d: '#1f5a3a', m: '#3f9a6f', l: '#7fd0a0', w: '#c8f5d8', p: '#0d1a12', y: '#d8e85a' },
    rows: [
      '................',
      '................',
      '................',
      '......oooo......',
      '.....ommmmo.....',
      '....omlwwlmo....',
      '...omlwyylmmo...',
      '...omlypyymdo...',
      '...omlyppymdo...',
      '...ommyypymdo...',
      '....ommyymdo....',
      '.....oddddo.....',
      '......oooo......',
      '................',
      '................',
      '................',
    ],
  },
  firework_rocket: {
    pal: { o: '#2a0e0e', r: '#d8423a', R: '#9a2620', w: '#f0f0f0', W: '#b8b8b8', p: '#d9caa0', k: '#28190a', h: '#896727', H: '#493615' },
    rows: [
      '................',
      '..........oo....',
      '.........owwo...',
      '........owwWWo..',
      '.......orrrrRo..',
      '......orwwwRo...',
      '.....orrrrRo....',
      '.....oRwwWo.....',
      '.....oRRRo......',
      '......ooh.......',
      '.....khH........',
      '....khH.........',
      '...khH..........',
      '..khH...........',
      '..kH............',
      '................',
    ],
  },
  firework_star: {
    pal: { o: '#1e1e1e', d: '#3a3a3a', m: '#5a5a5a', l: '#7a7a7a', c: '@3', C: '@2' },
    rows: [
      '................',
      '................',
      '......o..o......',
      '.....omoomo.....',
      '....omlmlmmo....',
      '...omlcclmldo...',
      '..omlcCCclmmo...',
      '..olmcCCCcmdo...',
      '...omcCCcmdo....',
      '...olmccmmdo....',
      '..omlmmdmdddo...',
      '..oddmo.oddo....',
      '...oo...oo......',
      '................',
      '................',
      '................',
    ],
  },
  lead: {
    pal: { o: '#3b2a1a', l: '#d9b98a', m: '#b08a5a', d: '#7a5a34' },
    rows: [
      '................',
      '.......oooo.....',
      '.....oollmmoo...',
      '....olmoooomdo..',
      '...olmo....omdo.',
      '...omo......odo.',
      '...omo......odo.',
      '...olmo....omdo.',
      '....olmoooomdo..',
      '.....oollmmmo...',
      '.......ooomdo...',
      '.........olmo...',
      '..........omdo..',
      '...........odo..',
      '............oo..',
      '................',
    ],
  },
  name_tag: {
    pal: { o: '#3b2a1a', t: '#e4d2a8', T: '#bfa678', s: '#d8d8d8', S: '#9a9a9a', d: '#8a6a40', h: '#5a4026' },
    rows: [
      '................',
      '.ss.............',
      's..s............',
      's...ss..........',
      '.s....s.........',
      '..ss...oooooo...',
      '....s.otttttto..',
      '.....odhtttttto.',
      '.....otttttttTo.',
      '......otttttTTo.',
      '.......otttTTo..',
      '........otTTo...',
      '.........oTo....',
      '..........o.....',
      '................',
      '................',
    ],
  },
  totem_of_undying: {
    pal: { o: '#4a2c08', y: '#fcee4b', Y: '#e9b115', G: '#b26411', g: '#2ecc71', e: '#0f6b3a', w: '#ffffb5' },
    rows: [
      '................',
      '.....oooooo.....',
      '....owyyyyYo....',
      '....oyegyegYo...',
      '....oyYYYYYYo...',
      '....oyyGGGyYo...',
      '.oo..oyYYYYo..oo',
      'oyyoooyyyyYoooYo',
      'oyYYYYyYYYYYYYGo',
      '.oooooyYGGYooooo',
      '.....oyYYYGo....',
      '.....oyYGYGo....',
      '....oyYYYYGGo...',
      '....oYGoooGGo...',
      '.....oo...oo....',
      '................',
    ],
  },
};

const TOOL_MAT = { wooden: 'wood', stone: 'stone', iron: 'iron', golden: 'gold', diamond: 'diamond', netherite: 'netherite', copper: 'copper', gold: 'gold', wood: 'wood' };
const mat = (name, m) => ({ a: TOOL_MAT[m[1]] });
const MATS = 'wooden|stone|iron|golden|diamond|netherite|copper';

export const rules = [
  [new RegExp(`^(${MATS})_sword$`), 'sword', mat],
  [new RegExp(`^(${MATS})_pickaxe$`), 'pickaxe', mat],
  [new RegExp(`^(${MATS})_axe$`), 'axe', mat],
  [new RegExp(`^(${MATS})_shovel$`), 'shovel', mat],
  [new RegExp(`^(${MATS})_hoe$`), 'hoe', mat],
  [new RegExp(`^(${MATS})_spear$`), 'spear', mat],
  // add-on weapons that read as a known tool
  [/^(wooden|stone|iron|golden|diamond|netherite|copper|gold|wood)_battle_axe$/, 'axe', mat],
  [/^hammer$/, 'axe', { a: 'iron' }],
  [/^staff$/, 'spear', { a: 'amethyst' }],
  [/^mace$/, 'mace'],
  [/^trident$/, 'trident'],
  [/^bow$/, 'bow'],
  [/^crossbow$/, 'crossbow'],
  [/^arrow$/, 'arrow', { a: '#f0f0f0', b: 'stone' }],
  [/^spectral_arrow$/, 'arrow', { a: '#fcee4b', b: 'gold' }],
  [/^tipped_arrow$/, 'arrow', { a: '#f0f0f0', b: '#c2449a' }],
  [/^shield$/, 'shield'],
  [/^fishing_rod$/, 'fishing_rod'],
  [/^carrot_on_a_stick$/, 'carrot_on_a_stick'],
  [/^warped_fungus_on_a_stick$/, 'warped_fungus_on_a_stick'],
  [/^shears$/, 'shears'],
  [/^flint_and_steel$/, 'flint_and_steel'],
  [/^brush$/, 'brush'],
  [/^spyglass$/, 'spyglass'],
  [/^(lodestone_)?compass$/, 'compass'],
  [/^recovery_compass$/, 'recovery_compass'],
  [/^clock$/, 'clock'],
  [/^goat_horn$/, 'goat_horn'],
  [/^trial_key$/, 'key', { a: ['#2a2420', '#4f4640', '#6e655c', '#8f857a', '#b3a89a', '#d8cdbd'], b: 'copper' }],
  [/^ominous_trial_key$/, 'key', { a: ['#141820', '#262d3a', '#38404f', '#4b5466', '#66708a', '#8a95b0'], b: '#3fb8b0' }],
  [/^wind_charge$/, 'wind_charge'],
  [/^fire_charge$/, 'fire_charge'],
  [/^snowball$/, 'snowball'],
  [/^egg$/, 'egg', { a: ['#5a4630', '#a08460', '#c8ad84', '#dfc8a0', '#efe0c0', '#fbf3e0'], b: ['#5a4630', '#8a6a48', '#b39070', '#c8a880', '#e0c8a0', '#f0e0c0'] }],
  [/^blue_egg$/, 'egg', { a: ['#2a4258', '#5a7ea0', '#7ea4c4', '#9cc0dc', '#bcd6ec', '#e0eefa'], b: ['#2a4258', '#4a6a8a', '#6a8aa8', '#8aa8c4', '#a8c4dc', '#c8dcf0'] }],
  [/^brown_egg$/, 'egg', { a: ['#3a2410', '#7a5030', '#a06c44', '#b88458', '#d0a070', '#e8c49a'], b: ['#3a2410', '#5a3a1e', '#7a5030', '#946440', '#b08058', '#c8a078'] }],
  [/^ender_pearl$/, 'ender_pearl'],
  [/^(ender_eye|eye_of_ender)$/, 'ender_eye'],
  [/^firework_rocket$/, 'firework_rocket'],
  [/^firework_star$/, 'firework_star', { a: '#e94e77' }],
  [/^lead$/, 'lead'],
  [/^name_tag$/, 'name_tag'],
  [/^totem_of_undying$/, 'totem_of_undying'],
];
