// Vanilla item ids (without namespace) used to review and test the item art: every non-block
// item plus a sample of blocks in each model shape.
const WOODS = ['oak', 'spruce', 'birch', 'jungle', 'acacia', 'dark_oak', 'mangrove', 'cherry', 'pale_oak', 'bamboo', 'crimson', 'warped'];
const COLORS = ['white', 'orange', 'magenta', 'light_blue', 'yellow', 'lime', 'pink', 'gray', 'light_gray', 'cyan', 'purple', 'blue', 'brown', 'green', 'red', 'black'];
const TOOL_MATS = ['wooden', 'stone', 'iron', 'golden', 'diamond', 'netherite', 'copper'];
const ARMOR_MATS = ['leather', 'chainmail', 'iron', 'golden', 'diamond', 'netherite', 'copper'];

export const VANILLA = [
  ...TOOL_MATS.flatMap(m => ['sword', 'pickaxe', 'axe', 'shovel', 'hoe', 'spear'].map(t => `${m}_${t}`)),
  ...ARMOR_MATS.flatMap(m => ['helmet', 'chestplate', 'leggings', 'boots'].map(t => `${m}_${t}`)),
  'turtle_helmet', 'leather_horse_armor', 'iron_horse_armor', 'golden_horse_armor', 'diamond_horse_armor', 'copper_horse_armor', 'netherite_horse_armor', 'wolf_armor',
  'elytra', 'shield', 'totem_of_undying', 'bow', 'crossbow', 'arrow', 'spectral_arrow', 'tipped_arrow', 'trident', 'mace', 'fishing_rod',
  'carrot_on_a_stick', 'warped_fungus_on_a_stick', 'shears', 'flint_and_steel', 'brush', 'spyglass', 'compass', 'recovery_compass', 'clock',
  'lead', 'name_tag', 'saddle', 'bucket', 'water_bucket', 'lava_bucket', 'milk_bucket', 'powder_snow_bucket', 'cod_bucket', 'salmon_bucket',
  'tropical_fish_bucket', 'pufferfish_bucket', 'axolotl_bucket', 'tadpole_bucket', 'trial_key', 'ominous_trial_key', 'wind_charge', 'fire_charge',
  'firework_rocket', 'firework_star', 'snowball', 'egg', 'blue_egg', 'brown_egg', 'ender_pearl', 'ender_eye', 'experience_bottle', 'goat_horn',
  'map', 'filled_map', 'book', 'writable_book', 'written_book', 'enchanted_book', 'knowledge_book', 'paper',
  'potion', 'splash_potion', 'lingering_potion', 'glass_bottle', 'honey_bottle', 'ominous_bottle', 'dragon_breath',
  'music_disc_13', 'music_disc_cat', 'music_disc_pigstep', 'music_disc_otherside', 'music_disc_5', 'disc_fragment_5', 'bundle', 'red_bundle',
  'minecart', 'chest_minecart', 'hopper_minecart', 'tnt_minecart', 'furnace_minecart', 'oak_boat', 'oak_chest_boat', 'spruce_boat', 'bamboo_raft',
  'armor_stand', 'item_frame', 'glow_item_frame', 'painting',
  'coal', 'charcoal', 'diamond', 'emerald', 'lapis_lazuli', 'quartz', 'amethyst_shard', 'echo_shard', 'redstone', 'glowstone_dust',
  'iron_ingot', 'gold_ingot', 'copper_ingot', 'netherite_ingot', 'netherite_scrap', 'iron_nugget', 'gold_nugget', 'copper_nugget',
  'raw_iron', 'raw_gold', 'raw_copper', 'stick', 'string', 'feather', 'leather', 'rabbit_hide', 'flint', 'bone', 'bone_meal', 'gunpowder',
  'sugar', 'blaze_rod', 'blaze_powder', 'breeze_rod', 'ghast_tear', 'magma_cream', 'slime_ball', 'clay_ball', 'brick', 'nether_brick',
  'ender_pearl', 'nether_star', 'shulker_shell', 'phantom_membrane', 'turtle_scute', 'armadillo_scute', 'nautilus_shell', 'heart_of_the_sea',
  'prismarine_shard', 'prismarine_crystals', 'honeycomb', 'ink_sac', 'glow_ink_sac', 'heavy_core', 'resin_clump', 'resin_brick',
  'fermented_spider_eye', 'spider_eye', 'rotten_flesh', 'dragon_breath',
  ...COLORS.map(c => `${c}_dye`),
  'netherite_upgrade_smithing_template', 'coast_armor_trim_smithing_template', 'flow_pottery_sherd', 'angler_pottery_sherd',
  'flower_banner_pattern', 'creeper_banner_pattern', 'piglin_banner_pattern', 'guster_banner_pattern',
  'apple', 'golden_apple', 'enchanted_golden_apple', 'bread', 'cookie', 'cake', 'pumpkin_pie', 'carrot', 'golden_carrot', 'potato', 'baked_potato',
  'poisonous_potato', 'beetroot', 'beetroot_soup', 'mushroom_stew', 'rabbit_stew', 'suspicious_stew', 'melon_slice', 'glistering_melon_slice',
  'sweet_berries', 'glow_berries', 'chorus_fruit', 'popped_chorus_fruit', 'dried_kelp', 'honey_bottle',
  'beef', 'cooked_beef', 'porkchop', 'cooked_porkchop', 'chicken', 'cooked_chicken', 'mutton', 'cooked_mutton', 'rabbit', 'cooked_rabbit',
  'cod', 'cooked_cod', 'salmon', 'cooked_salmon', 'tropical_fish', 'pufferfish', 'rabbit_foot',
  'wheat', 'wheat_seeds', 'pumpkin_seeds', 'melon_seeds', 'beetroot_seeds', 'torchflower_seeds', 'pitcher_pod', 'cocoa_beans', 'nether_wart',
  'sugar_cane', 'bamboo', 'kelp', 'cactus_flower',
  'poppy', 'dandelion', 'blue_orchid', 'allium', 'azure_bluet', 'red_tulip', 'orange_tulip', 'white_tulip', 'pink_tulip', 'oxeye_daisy',
  'cornflower', 'lily_of_the_valley', 'wither_rose', 'torchflower', 'sunflower', 'lilac', 'rose_bush', 'peony', 'pitcher_plant',
  'open_eyeblossom', 'closed_eyeblossom', 'pink_petals', 'wildflowers', 'leaf_litter',
  ...WOODS.filter(w => !['bamboo', 'crimson', 'warped'].includes(w)).map(w => `${w}_sapling`), 'mangrove_propagule', 'azalea', 'flowering_azalea',
  'brown_mushroom', 'red_mushroom', 'crimson_fungus', 'warped_fungus', 'crimson_roots', 'warped_roots', 'nether_sprouts', 'weeping_vines', 'twisting_vines',
  'short_grass', 'tall_grass', 'fern', 'large_fern', 'dead_bush', 'bush', 'firefly_bush', 'short_dry_grass', 'tall_dry_grass', 'seagrass',
  'sea_pickle', 'lily_pad', 'vine', 'glow_lichen', 'hanging_roots', 'spore_blossom', 'big_dripleaf', 'small_dripleaf', 'cobweb',
  'tube_coral', 'brain_coral_fan', 'chorus_flower',
  ...WOODS.slice(0, 3).flatMap(w => [`${w}_door`, `${w}_sign`, `${w}_hanging_sign`]), 'iron_door', 'copper_door',
  'torch', 'soul_torch', 'redstone_torch', 'copper_torch', 'lantern', 'soul_lantern', 'copper_lantern', 'candle', 'red_candle', 'white_bed', 'red_bed',
  'white_banner', 'red_banner', 'rail', 'powered_rail', 'detector_rail', 'activator_rail', 'ladder', 'lever', 'tripwire_hook', 'chain',
  'iron_bars', 'glass_pane', 'red_stained_glass_pane', 'flower_pot', 'decorated_pot', 'cauldron', 'hopper', 'brewing_stand', 'campfire',
  'soul_campfire', 'bell', 'repeater', 'comparator', 'lightning_rod', 'pointed_dripstone', 'end_rod', 'skeleton_skull', 'wither_skeleton_skull',
  'zombie_head', 'creeper_head', 'player_head', 'piglin_head', 'dragon_head', 'dragon_egg', 'turtle_egg', 'sniffer_egg', 'frog_spawn',
  'cow_spawn_egg', 'zombie_spawn_egg', 'creeper_spawn_egg', 'iron_golem_spawn_egg', 'sculk_sensor', 'amethyst_cluster', 'conduit', 'beacon',
  'stone', 'cobblestone', 'grass_block', 'dirt', 'oak_planks', 'oak_log', 'oak_leaves', 'glass', 'white_wool', 'red_concrete', 'diamond_ore',
  'deepslate_iron_ore', 'iron_block', 'gold_block', 'diamond_block', 'bricks', 'stone_bricks', 'oak_stairs', 'stone_slab', 'cobblestone_wall',
  'oak_fence', 'oak_trapdoor', 'crafting_table', 'furnace', 'chest', 'barrel', 'bookshelf', 'tnt', 'pumpkin', 'carved_pumpkin', 'jack_o_lantern',
  'melon', 'hay_block', 'sand', 'gravel', 'netherrack', 'obsidian', 'white_carpet', 'shulker_box', 'red_shulker_box', 'ender_chest', 'anvil',
  'respawn_anchor', 'lodestone', 'target', 'beehive', 'bee_nest', 'honey_block', 'honeycomb_block', 'sea_lantern', 'shroomlight', 'nether_wart_block', 'warped_wart_block',
  'crimson_nylium', 'warped_nylium', 'chorus_plant', 'mangrove_roots', 'muddy_mangrove_roots', 'rooted_dirt', 'packed_mud', 'mud_bricks', 'reinforced_deepslate',
  'sculk_catalyst', 'sculk_shrieker', 'calibrated_sculk_sensor', 'suspicious_sand', 'suspicious_gravel', 'crying_obsidian', 'ancient_debris', 'nether_gold_ore',
  'amethyst_block', 'budding_amethyst', 'spawner', 'trial_spawner', 'vault', 'crafter', 'smithing_table', 'cartography_table', 'fletching_table', 'loom', 'stonecutter',
  'grindstone', 'enchanting_table', 'jukebox', 'note_block', 'creaking_heart', 'resin_block', 'resin_bricks', 'chiseled_resin_bricks', 'dried_kelp_block',
  'ochre_froglight', 'verdant_froglight', 'pearlescent_froglight', 'scaffolding', 'moss_block', 'moss_carpet', 'oak_shelf', 'stone_brick_stairs',
  'end_crystal', 'debug_stick', 'bowl', 'white_harness', 'red_harness', 'iron_nautilus_armor', 'golden_nautilus_armor', 'diamond_nautilus_armor', 'netherite_nautilus_armor',
  'copper_nautilus_armor', 'light', 'structure_void', 'cave_vines', 'heart_pottery_sherd', 'skull_pottery_sherd', 'music_disc_creator', 'music_disc_precipice',
  'music_disc_relic', 'music_disc_lava_chicken', 'music_disc_tears',
];

