// 16×16 pixel-art item sprites drawn here (no game textures are shipped). Each template uses
// palette letters filled from the item's material colour:
//   o outline · a base · b highlight · c shade · h handle · H handle shade · w white glint · s accent
// Blocks are drawn as an isometric cube from the surface-map colour.

const T = {
  sword: [
    '..............oo',
    '.............obo',
    '............obao',
    '...........obao.',
    '..........obao..',
    '.........obao...',
    '........obao....',
    '..oo...obao.....',
    '..oco.obao......',
    '...ocobao.......',
    '....occo........',
    '....oHoco.......',
    '...oHo.oco......',
    '..oHo...oo......',
    '.oso............',
    '.oo.............',
  ],
  pickaxe: [
    '................',
    '....ooooooo.....',
    '...obbbbbbaoo...',
    '....oooooobaao..',
    '..........ohcao.',
    '.........ohoocao',
    '........ohHo.oco',
    '.......ohHo..oco',
    '......ohHo....oo',
    '.....ohHo.......',
    '....ohHo........',
    '...ohHo.........',
    '..ohHo..........',
    '.ohHo...........',
    '.oHo............',
    '..o.............',
  ],
  axe: [
    '................',
    '.......ooo......',
    '......obbaoo....',
    '.....obbaaaoo...',
    '.....obaaaaco...',
    '......oaaaccHo..',
    '.......ooccohHo.',
    '.........ohHo...',
    '........ohHo....',
    '.......ohHo.....',
    '......ohHo......',
    '.....ohHo.......',
    '....ohHo........',
    '...ohHo.........',
    '...oHo..........',
    '....o...........',
  ],
  shovel: [
    '................',
    '...........ooo..',
    '..........obbao.',
    '.........obbaaao',
    '.........obaaaco',
    '..........oaacco',
    '.........ohoooo.',
    '........ohHo....',
    '.......ohHo.....',
    '......ohHo......',
    '.....ohHo.......',
    '....ohHo........',
    '...ohHo.........',
    '..ohHo..........',
    '..oHo...........',
    '...o............',
  ],
  hoe: [
    '................',
    '.......ooooo....',
    '......obbbaaoo..',
    '.......ooooocao.',
    '..........ohoco.',
    '.........ohHooo.',
    '........ohHo....',
    '.......ohHo.....',
    '......ohHo......',
    '.....ohHo.......',
    '....ohHo........',
    '...ohHo.........',
    '..ohHo..........',
    '..oHo...........',
    '...o............',
    '................',
  ],
  ingot: [
    '................',
    '................',
    '................',
    '................',
    '.....oooooooo...',
    '....obbbbbbbao..',
    '...obbbbbbbaao..',
    '..oaaaaaaaaaco..',
    '..oaaaaaaaaco...',
    '..occcccccco....',
    '...oooooooo.....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  gem: [
    '................',
    '................',
    '....oooooooo....',
    '...obbwbbbbao...',
    '..obwbbabbaaao..',
    '.obbbaaaaaaaaco.',
    '.oaaaaaaaaaaaco.',
    '..oaaaaaaaaacco.',
    '...oaaaaaaacco..',
    '....oaaaaacco...',
    '.....oaaacco....',
    '......oacco.....',
    '.......oco......',
    '........o.......',
    '................',
    '................',
  ],
  nugget: [
    '................',
    '................',
    '................',
    '................',
    '.....oooo.......',
    '....obbaaoo.....',
    '...obwbaaaaoo...',
    '...obaaaaaacco..',
    '....oaaaaacco...',
    '.....oocccoo....',
    '.......ooo......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  dust: [
    '................',
    '................',
    '................',
    '................',
    '.......o........',
    '......obo.......',
    '.....obaao......',
    '....obaaaao.....',
    '...obaabaaco....',
    '..obaaaaaaacoo..',
    '.obaabaaaaaaaco.',
    '.occcccccccccco.',
    '..oooooooooooo..',
    '................',
    '................',
    '................',
  ],
  stick: [
    '................',
    '.............oo.',
    '............obo.',
    '...........obao.',
    '..........obao..',
    '.........obao...',
    '........obao....',
    '.......obao.....',
    '......obao......',
    '.....obao.......',
    '....obao........',
    '...obao.........',
    '..obao..........',
    '..oao...........',
    '...o............',
    '................',
  ],
  helmet: [
    '................',
    '................',
    '................',
    '....oooooooo....',
    '...obbbbbbbao...',
    '..obbaaaaaaaco..',
    '..obaaaaaaaaco..',
    '..obaoooooocco..',
    '..obao....occo..',
    '..oaao....occo..',
    '..oooo....oooo..',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  chestplate: [
    '................',
    '..ooo......ooo..',
    '.obbaoooooobaao.',
    '.obaaabbbbaaaco.',
    '.obaaaaaaaaaaco.',
    '.oooaaaaaaaaooo.',
    '...obaaaaaaco...',
    '...obaaaaaaco...',
    '...obaaaaaaco...',
    '...obaaaaaaco...',
    '...obaaaaaaco...',
    '...occccccccco..',
    '...oooooooooo...',
    '................',
    '................',
    '................',
  ],
  leggings: [
    '................',
    '...oooooooooo...',
    '...obbbbbbbao...',
    '...obaaaaaaco...',
    '...obaaooaaco...',
    '...obao..obco...',
    '...obao..obco...',
    '...obao..obco...',
    '...obao..obco...',
    '...obao..obco...',
    '...occo..occo...',
    '...oooo..oooo...',
    '................',
    '................',
    '................',
    '................',
  ],
  boots: [
    '................',
    '................',
    '................',
    '................',
    '...oooo..oooo...',
    '...obao..obao...',
    '...obao..obao...',
    '...obao..obao...',
    '..obaao.obaao...',
    '.obaaao.obaaaoo.',
    '.occcco.occccco.',
    '.oooooo.ooooooo.',
    '................',
    '................',
    '................',
    '................',
  ],
  apple: [
    '................',
    '.........o......',
    '........oHo.....',
    '.......ohoss....',
    '....oooooosso...',
    '...obbaoaaaoo...',
    '..obwbaaaaaaco..',
    '..obbaaaaaaaco..',
    '..obaaaaaaaaco..',
    '..oaaaaaaaaaco..',
    '..oaaaaaaaaco...',
    '...oaaaaaacco...',
    '....occccco.....',
    '.....ooooo......',
    '................',
    '................',
  ],
  meat: [
    '................',
    '................',
    '.......ooooo....',
    '.....oobbaaaoo..',
    '....obbaaaaaaco.',
    '...obaaaaaaaaco.',
    '...obaaaaaaaaco.',
    '...oaaaaaaaacco.',
    '....oaaaaaacco..',
    '....ooccccccoo..',
    '...owwooooooo...',
    '..owwo..........',
    '.owwo...........',
    '.oowo...........',
    '..oo............',
    '................',
  ],
  fish: [
    '................',
    '................',
    '................',
    '................',
    '......ooooo.....',
    '....oobbbbaoo.oo',
    '...obwbaaaaaaoao',
    '..obobaaaaaaacao',
    '..obaaaaaaaaaco.',
    '...occaaaaaacco.',
    '....ooccccccoo.o',
    '......oooooo..oo',
    '................',
    '................',
    '................',
    '................',
  ],
  potion: [
    '................',
    '......oooo......',
    '......oHHo......',
    '.......oo.......',
    '......owwo......',
    '......owwo......',
    '.....owwwwo.....',
    '....owbaaaao....',
    '...owbaaaaaao...',
    '...obaaaaaaco...',
    '...oaaaaaaaco...',
    '...oaaaaaacco...',
    '....occccccco...',
    '.....oooooooo...',
    '................',
    '................',
  ],
  book: [
    '................',
    '................',
    '...ooooooooooo..',
    '..obbbbbbbbbbao.',
    '..obaaaaaaaaaco.',
    '..obaasssssaaco.',
    '..obaaaaaaaaaco.',
    '..obaasssaaaaco.',
    '..obaaaaaaaaaco.',
    '..obaaaaaaaaaco.',
    '..oaaaaaaaaaaco.',
    '..owwwwwwwwwwwo.',
    '..ocwwwwwwwwwwo.',
    '...ooooooooooo..',
    '................',
    '................',
  ],
  map: [
    '................',
    '..oooooooooooo..',
    '..obbbbbbbbbbo..',
    '..obasaaaabsao..',
    '..obaassabbaao..',
    '..obaaasaaaaco..',
    '..obbaaaassaco..',
    '..obasaaaaasao..',
    '..obaaabbaaaco..',
    '..obaasaasaaco..',
    '..obaaaaaaaaco..',
    '..ocbbacaaccco..',
    '..oooooooooooo..',
    '................',
    '................',
    '................',
  ],
  orb: [
    '................',
    '................',
    '................',
    '.....oooooo.....',
    '....obbbaaao....',
    '...obwbaaaaco...',
    '...obbaaaaaco...',
    '...obaaaaaaco...',
    '...oaaaaaacco...',
    '...oaaaaaacco...',
    '....occcccco....',
    '.....oooooo.....',
    '................',
    '................',
    '................',
    '................',
  ],
  egg: [
    '................',
    '................',
    '.......oo.......',
    '......obao......',
    '.....obwaao.....',
    '....obbaaaao....',
    '....obasaaco....',
    '...obaaaasaco...',
    '...obaasaaaco...',
    '...oaaaaaaaco...',
    '...oaaaaaacco...',
    '....occcccco....',
    '.....oooooo.....',
    '................',
    '................',
    '................',
  ],
  totem: [
    '................',
    '.....oooooo.....',
    '....obbbbbao....',
    '....obsaasao....',
    '....obaaaaao....',
    '....oaasssao....',
    '..oooaaaaaaooo..',
    '.obbaaaaaaaaaco.',
    '.oaaoaaaaaaocco.',
    '..oo.obaaaco.oo.',
    '.....obaaaco....',
    '.....obaoaco....',
    '.....oaao.oco...',
    '.....ooo..ooo...',
    '................',
    '................',
  ],
  elytra: [
    '................',
    '..oooo....oooo..',
    '.obbbao..obbbao.',
    '.obaaao..obaaao.',
    '.obaaaao.obaaao.',
    '.obaaaao.obaaao.',
    '.obaaaaooobaaao.',
    '.obaasao..oaaao.',
    '.obaasao..oasao.',
    '.obaasao..oasao.',
    '.oaaaco...oaaco.',
    '..oacco....occo.',
    '...oco......oo..',
    '....o...........',
    '................',
    '................',
  ],
  bow: [
    '................',
    '.......oooo.....',
    '......ohhhho....',
    '.....oho...os...',
    '....oho....os...',
    '...oho....os....',
    '...oho...os.....',
    '..ohHo..os......',
    '..ohHo.os.......',
    '...ohHoos.......',
    '...ohHos........',
    '....ohos........',
    '.....oso........',
    '......o.........',
    '................',
    '................',
  ],
  arrow: [
    '................',
    '..........oooo..',
    '..........obbo..',
    '...........oao..',
    '..........ohooo.',
    '.........ohHo...',
    '........ohHo....',
    '.......ohHo.....',
    '......ohHo......',
    '.....ohHo.......',
    '...oowHo........',
    '...owwo.........',
    '...owwo.........',
    '....oo..........',
    '................',
    '................',
  ],
  bucket: [
    '................',
    '................',
    '....oooooooo....',
    '...o........o...',
    '..o..........o..',
    '..oooooooooooo..',
    '..obssssssssao..',
    '..obbbbbbbbaco..',
    '...obaaaaaaco...',
    '...obaaaaaaco...',
    '...obaaaaaaco...',
    '....oaaaaaco....',
    '....occccco.....',
    '.....oooooo.....',
    '................',
    '................',
  ],
  disc: [
    '................',
    '.....oooooo.....',
    '....oaaaaaao....',
    '...oaasssaaao...',
    '..oaasaaaasaao..',
    '..oasaawwaasao..',
    '..oasawooaasao..',
    '..oasaaooaasao..',
    '..oaasaaaasaao..',
    '...oaasssaaao...',
    '....oaaaaaao....',
    '.....oooooo.....',
    '................',
    '................',
    '................',
    '................',
  ],
  shield: [
    '................',
    '..oooooooooooo..',
    '..obbbbbbbbbao..',
    '..obaaasaaaaco..',
    '..obaasssaaaco..',
    '..obaaasaaaaco..',
    '..obaaaaaaaaco..',
    '..obaaaaaaaaco..',
    '...obaaaaaaco...',
    '...obaaaaaaco...',
    '....oaaaaaco....',
    '.....oacco......',
    '......oo........',
    '................',
    '................',
    '................',
  ],
  coil: [
    '................',
    '................',
    '.....oooooo.....',
    '....obbbbbbo....',
    '...obaooooaao...',
    '...obo....oao...',
    '...obaooooaao...',
    '...obbbbbbaco...',
    '...obaooooaco...',
    '...obo....oco...',
    '...obaooooaco...',
    '....occcccco....',
    '.....oooooo.....',
    '................',
    '................',
    '................',
  ],
  bone: [
    '................',
    '.............oo.',
    '............obbo',
    '..........oobaao',
    '.........obaaoo.',
    '........obao....',
    '.......obao.....',
    '......obao......',
    '.....obao.......',
    '....obao........',
    '.ooobao.........',
    'obbaao..........',
    'obaao...........',
    '.oao............',
    '..o.............',
    '................',
  ],
  feather: [
    '................',
    '...........ooo..',
    '..........obbbo.',
    '.........obbaao.',
    '........obbaaco.',
    '.......obbaaco..',
    '......obbaaco...',
    '.....obbaaco....',
    '....obbaaco.....',
    '...obaaaco......',
    '...obaaco.......',
    '...oacco........',
    '..ohoo..........',
    '.oho............',
    '.oo.............',
    '................',
  ],
  seeds: [
    '................',
    '................',
    '................',
    '................',
    '........oo......',
    '.....oo.obo.....',
    '....obo.oao.oo..',
    '....oao..o.obo..',
    '.oo..o..oo.oao..',
    'obo....obo..o...',
    'oao.oo.oao..oo..',
    '.o.obo..o..obo..',
    '...oao.....oao..',
    '....o.......o...',
    '................',
    '................',
  ],
  plant: [
    '................',
    '.......oo.......',
    '......osso......',
    '.....osbbso.....',
    '......osso......',
    '.......oo.......',
    '....oo.oo.......',
    '...obbooHo......',
    '...obaaoHo.oo...',
    '....oooohooaao..',
    '.......oHobaao..',
    '.......oHooo....',
    '.......oHo......',
    '.......oHo......',
    '.......ooo......',
    '................',
  ],
  torch: [
    '................',
    '................',
    '.......oo.......',
    '......owwo......',
    '......obso......',
    '......osso......',
    '.......oo.......',
    '......oHho......',
    '......oHho......',
    '......oHho......',
    '......oHho......',
    '......oHho......',
    '......oHho......',
    '.......oo.......',
    '................',
    '................',
  ],
  key: [
    '................',
    '................',
    '..oooo..........',
    '.obbbao.........',
    '.obooao.........',
    '.obooao.........',
    '.oaaaaoooooooo..',
    '..oaccbbbbbbbao.',
    '...ooooooaoaoo..',
    '.........oo.oo..',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  rocket: [
    '................',
    '.............o..',
    '............obo.',
    '...........obao.',
    '..........obao..',
    '.........obaso..',
    '........obasao..',
    '.......obasao...',
    '......obaaao....',
    '.....oaaaao.....',
    '....ocaaao......',
    '...ohoccoo......',
    '..ohoo..........',
    '.oho............',
    '.oo.............',
    '................',
  ],
  box: [
    '................',
    '..oooooooooooo..',
    '..obbbbbbbbbbo..',
    '..obaaaaaaaaco..',
    '..obaaaaaaaaco..',
    '..ocwccccccwco..',
    '..ooooossoooooo.',
    '..obaaossoaaaco.',
    '..obaaaaaaaaco..',
    '..obaaaaaaaaco..',
    '..obaaaaaaaaco..',
    '..occcccccccco..',
    '..oooooooooooo..',
    '................',
    '................',
    '................',
  ],
  door: [
    '................',
    '....oooooooo....',
    '....obbbbbao....',
    '....obooooao....',
    '....obaaaaao....',
    '....obooooao....',
    '....obaaaaao....',
    '....obaaaaso....',
    '....obaaaaao....',
    '....obooooao....',
    '....obaaaaao....',
    '....obooooao....',
    '....ocaaaaco....',
    '....oooooooo....',
    '................',
    '................',
  ],
};
// Cube: top face b, left face a, right face c, edges o; "ore" sprinkles s.
T.block = [
  '................',
  '.......oo.......',
  '.....oobboo.....',
  '...oobbbbbboo...',
  '.oobbbbbbbbbboo.',
  '.oaabbbbbbbbcco.',
  '.oaaaabbbbcccco.',
  '.oaaaaaoocccccco',
  '.oaaaaaaocccccco',
  '.oaaaaaaocccccco',
  '.oaaaaaaocccccco',
  '.oaaaaaaocccccco',
  '..ooaaaaocccoo..',
  '....ooaaocoo....',
  '......oooo......',
  '................',
];
T.ore = T.block.map((r, y) => [...r].map((ch, x) => ((ch !== '.' && ch !== 'o' && (x * 7 + y * 5) % 11 === 0) ? 's' : ch)).join(''));

const SHAPE_RULES = [
  [/_sword$/, 'sword'], [/_pickaxe$/, 'pickaxe'], [/_axe$/, 'axe'], [/_shovel$/, 'shovel'], [/_hoe$/, 'hoe'],
  [/_helmet$|turtle_helmet/, 'helmet'], [/_chestplate$/, 'chestplate'], [/_leggings$/, 'leggings'], [/_boots$/, 'boots'],
  [/horse_armor|wolf_armor/, 'chestplate'], [/shield/, 'shield'], [/elytra/, 'elytra'], [/totem/, 'totem'],
  [/^bow$|crossbow/, 'bow'], [/arrow|trident/, 'arrow'], [/spawn_egg|^egg$|turtle_egg|sniffer_egg/, 'egg'],
  [/ingot|netherite_scrap|brick$/, 'ingot'], [/nugget|^coal$|^charcoal$|raw_(iron|gold|copper)$/, 'nugget'],
  [/^diamond$|^emerald$|amethyst_shard|^quartz$|prismarine_crystals|echo_shard|lapis_lazuli|nether_star/, 'gem'],
  [/redstone$|gunpowder|glowstone_dust|sugar$|blaze_powder|bone_meal|_dye$|^dye$/, 'dust'],
  [/^stick$|blaze_rod|breeze_rod|end_rod|fishing_rod|on_a_stick/, 'stick'], [/bone$/, 'bone'], [/feather/, 'feather'],
  [/enchanted_book|^book$|writable_book|written_book|knowledge_book/, 'book'], [/map$|paper|banner_pattern/, 'map'],
  [/compass|clock|ender_pearl|ender_eye|slime_ball|magma_cream|snowball|heart_of_the_sea|fire_charge|clay_ball|xp|experience/, 'orb'],
  [/potion|bottle|honey_bottle/, 'potion'], [/bucket/, 'bucket'], [/music_disc/, 'disc'],
  [/apple|melon_slice|beetroot$|potato|carrot|berries|chorus_fruit|cookie|bread|pie|cake$|stew|soup|kelp$/, 'apple'],
  [/beef|porkchop|mutton|chicken|rabbit$|cooked_|rotten_flesh|spider_eye/, 'meat'], [/cod|salmon|fish/, 'fish'],
  [/string|lead|name_tag|cobweb|chain$/, 'coil'], [/seeds|wart|cocoa/, 'seeds'],
  [/sapling|flower|tulip|poppy|dandelion|orchid|allium|bluet|daisy|cornflower|lily|rose|lilac|peony|fern|bush|azalea|propagule|mushroom$|fungus/, 'plant'],
  [/torch|lantern|candle/, 'torch'], [/key/, 'key'], [/firework|rocket/, 'rocket'],
  [/chest|barrel|shulker_box|bundle|crate|hopper/, 'box'], [/door|trapdoor/, 'door'], [/_ore$|ancient_debris/, 'ore'],
];

/** Which template an item id uses; blocks fall back to the cube. */
export function spriteShape(name, isItemish) {
  for (const [re, shape] of SHAPE_RULES) if (re.test(name)) return shape;
  return isItemish ? 'orb' : 'block';
}

// --- colour helpers -------------------------------------------------------
function rgb(color) {
  if (color.startsWith('#')) {
    const n = parseInt(color.slice(1), 16);
    return [n >> 16 & 255, n >> 8 & 255, n & 255];
  }
  const m = color.match(/\d+(\.\d+)?/g)?.map(Number) || [128, 128, 128];
  if (color.startsWith('hsl')) {
    const [h, s, l] = [m[0], m[1] / 100, m[2] / 100];
    const k = n => (n + h / 30) % 12, a = s * Math.min(l, 1 - l);
    const f = n => l - a * Math.max(-1, Math.min(k(n) - 3, 9 - k(n), 1));
    return [f(0), f(8), f(4)].map(v => Math.round(v * 255));
  }
  return m.slice(0, 3);
}
const mix = (c, t, p) => c.map((v, i) => Math.round(v + (t[i] - v) * p));
const hex = c => `#${c.map(v => Math.max(0, Math.min(255, v)).toString(16).padStart(2, '0')).join('')}`;
const lum = c => (0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2]) / 255;

function palette(color, accent) {
  const base = rgb(color);
  const dark = lum(base) < 0.22;
  return {
    a: hex(base),
    b: hex(mix(base, [255, 255, 255], dark ? 0.28 : 0.38)),
    c: hex(mix(base, [0, 0, 0], 0.3)),
    o: hex(mix(base, [0, 0, 0], dark ? 0.55 : 0.7)),
    w: '#ffffff',
    h: '#9b7448', H: '#6b4a2b',
    s: accent || hex(mix(base, [255, 255, 255], 0.65)),
  };
}

const cache = new Map();

/** data: URL of an SVG sprite for the given template and material colour. */
export function spriteUrl(shape, color, accent) {
  const key = `${shape}|${color}|${accent || ''}`;
  let url = cache.get(key);
  if (url) return url;
  const pal = palette(color, accent);
  const rows = T[shape] || T.orb;
  let rects = '';
  rows.forEach((row, y) => {
    for (let x = 0; x < 16;) {
      const ch = row[x];
      if (ch === '.' || ch === undefined) { x++; continue; }
      let w = 1;
      while (row[x + w] === ch) w++;
      rects += `<rect x="${x}" y="${y}" width="${w}" height="1" fill="${pal[ch] || pal.a}"/>`;
      x += w;
    }
  });
  url = `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">${rects}</svg>`)}`;
  cache.set(key, url);
  return url;
}

export const SPRITE_SHAPES = Object.keys(T);
